" MIT License. Copyright © Peter Kenny
function! f#snh#Snh()
  command! -range=% -nargs=? Snh <line1>,<line2>call s:Snh(<q-args>)
endfunction
" =============================================================================
"                                      Snh
" Substitute named with hexadecimal
" -----------------------------------------------------------------------------
function! s:Snh(q = '')
  sm_\C\\\@<!&acE;_\&#x223e;\&#x333;_geI
  sm_\C\\\@<!&bne;_\&#x3d;\&#x20e5;_geI
  sm_\C\\\@<!&bnequiv;_\&#x2261;\&#x20e5;_geI
  sm_\C\\\@<!&caps;_\&#x2229;\&#xfe00;_geI
  sm_\C\\\@<!&cups;_\&#x222a;\&#xfe00;_geI
  sm_\C\\\@<!&fjlig;_\&#x66;\&#x6a;_geI
  sm_\C\\\@<!&gesl;_\&#x22db;\&#xfe00;_geI
  sm_\C\\\@<!&gvertneqq;_\&#x2269;\&#xfe00;_geI
  sm_\C\\\@<!&gvnE;_\&#x2269;\&#xfe00;_geI
  sm_\C\\\@<!&lates;_\&#x2aad;\&#xfe00;_geI
  sm_\C\\\@<!&lesg;_\&#x22da;\&#xfe00;_geI
  sm_\C\\\@<!&lvertneqq;_\&#x2268;\&#xfe00;_geI
  sm_\C\\\@<!&lvnE;_\&#x2268;\&#xfe00;_geI
  sm_\C\\\@<!&nang;_\&#x2220;\&#x20d2;_geI
  sm_\C\\\@<!&napE;_\&#x2a70;\&#x338;_geI
  sm_\C\\\@<!&napid;_\&#x224b;\&#x338;_geI
  sm_\C\\\@<!&nbump;_\&#x224e;\&#x338;_geI
  sm_\C\\\@<!&nbumpe;_\&#x224f;\&#x338;_geI
  sm_\C\\\@<!&ncongdot;_\&#x2a6d;\&#x338;_geI
  sm_\C\\\@<!&nedot;_\&#x2250;\&#x338;_geI
  sm_\C\\\@<!&nesim;_\&#x2242;\&#x338;_geI
  sm_\C\\\@<!&ngE;_\&#x2267;\&#x338;_geI
  sm_\C\\\@<!&ngeqq;_\&#x2267;\&#x338;_geI
  sm_\C\\\@<!&ngeqslant;_\&#x2a7e;\&#x338;_geI
  sm_\C\\\@<!&nges;_\&#x2a7e;\&#x338;_geI
  sm_\C\\\@<!&nGg;_\&#x22d9;\&#x338;_geI
  sm_\C\\\@<!&nGt;_\&#x226b;\&#x20d2;_geI
  sm_\C\\\@<!&nGtv;_\&#x226b;\&#x338;_geI
  sm_\C\\\@<!&nlE;_\&#x2266;\&#x338;_geI
  sm_\C\\\@<!&nleqq;_\&#x2266;\&#x338;_geI
  sm_\C\\\@<!&nleqslant;_\&#x2a7d;\&#x338;_geI
  sm_\C\\\@<!&nles;_\&#x2a7d;\&#x338;_geI
  sm_\C\\\@<!&nLl;_\&#x22d8;\&#x338;_geI
  sm_\C\\\@<!&nLt;_\&#x226a;\&#x20d2;_geI
  sm_\C\\\@<!&nLtv;_\&#x226a;\&#x338;_geI
  sm_\C\\\@<!&NotEqualTilde;_\&#x2242;\&#x338;_geI
  sm_\C\\\@<!&NotGreaterFullEqual;_\&#x2267;\&#x338;_geI
  sm_\C\\\@<!&NotGreaterGreater;_\&#x226b;\&#x338;_geI
  sm_\C\\\@<!&NotGreaterSlantEqual;_\&#x2a7e;\&#x338;_geI
  sm_\C\\\@<!&NotHumpDownHump;_\&#x224e;\&#x338;_geI
  sm_\C\\\@<!&NotHumpEqual;_\&#x224f;\&#x338;_geI
  sm_\C\\\@<!&notindot;_\&#x22f5;\&#x338;_geI
  sm_\C\\\@<!&notinE;_\&#x22f9;\&#x338;_geI
  sm_\C\\\@<!&NotLeftTriangleBar;_\&#x29cf;\&#x338;_geI
  sm_\C\\\@<!&NotLessLess;_\&#x226a;\&#x338;_geI
  sm_\C\\\@<!&NotLessSlantEqual;_\&#x2a7d;\&#x338;_geI
  sm_\C\\\@<!&NotNestedGreaterGreater;_\&#x2aa2;\&#x338;_geI
  sm_\C\\\@<!&NotNestedLessLess;_\&#x2aa1;\&#x338;_geI
  sm_\C\\\@<!&NotPrecedesEqual;_\&#x2aaf;\&#x338;_geI
  sm_\C\\\@<!&NotRightTriangleBar;_\&#x29d0;\&#x338;_geI
  sm_\C\\\@<!&NotSquareSubset;_\&#x228f;\&#x338;_geI
  sm_\C\\\@<!&NotSquareSuperset;_\&#x2290;\&#x338;_geI
  sm_\C\\\@<!&NotSubset;_\&#x2282;\&#x20d2;_geI
  sm_\C\\\@<!&NotSucceedsEqual;_\&#x2ab0;\&#x338;_geI
  sm_\C\\\@<!&NotSucceedsTilde;_\&#x227f;\&#x338;_geI
  sm_\C\\\@<!&NotSuperset;_\&#x2283;\&#x20d2;_geI
  sm_\C\\\@<!&nparsl;_\&#x2afd;\&#x20e5;_geI
  sm_\C\\\@<!&npart;_\&#x2202;\&#x338;_geI
  sm_\C\\\@<!&npre;_\&#x2aaf;\&#x338;_geI
  sm_\C\\\@<!&npreceq;_\&#x2aaf;\&#x338;_geI
  sm_\C\\\@<!&nrarrc;_\&#x2933;\&#x338;_geI
  sm_\C\\\@<!&nrarrw;_\&#x219d;\&#x338;_geI
  sm_\C\\\@<!&nsce;_\&#x2ab0;\&#x338;_geI
  sm_\C\\\@<!&nsubE;_\&#x2ac5;\&#x338;_geI
  sm_\C\\\@<!&nsubset;_\&#x2282;\&#x20d2;_geI
  sm_\C\\\@<!&nsubseteqq;_\&#x2ac5;\&#x338;_geI
  sm_\C\\\@<!&nsucceq;_\&#x2ab0;\&#x338;_geI
  sm_\C\\\@<!&nsupE;_\&#x2ac6;\&#x338;_geI
  sm_\C\\\@<!&nsupset;_\&#x2283;\&#x20d2;_geI
  sm_\C\\\@<!&nsupseteqq;_\&#x2ac6;\&#x338;_geI
  sm_\C\\\@<!&nvap;_\&#x224d;\&#x20d2;_geI
  sm_\C\\\@<!&nvge;_\&#x2265;\&#x20d2;_geI
  sm_\C\\\@<!&nvgt;_\&#x3e;\&#x20d2;_geI
  sm_\C\\\@<!&nvle;_\&#x2264;\&#x20d2;_geI
  sm_\C\\\@<!&nvlt;_\&#x3c;\&#x20d2;_geI
  sm_\C\\\@<!&nvltrie;_\&#x22b4;\&#x20d2;_geI
  sm_\C\\\@<!&nvrtrie;_\&#x22b5;\&#x20d2;_geI
  sm_\C\\\@<!&nvsim;_\&#x223c;\&#x20d2;_geI
  sm_\C\\\@<!&race;_\&#x223d;\&#x331;_geI
  sm_\C\\\@<!&smtes;_\&#x2aac;\&#xfe00;_geI
  sm_\C\\\@<!&sqcaps;_\&#x2293;\&#xfe00;_geI
  sm_\C\\\@<!&sqcups;_\&#x2294;\&#xfe00;_geI
  sm_\C\\\@<!&ThickSpace;_\&#x205f;\&#x200a;_geI
  sm_\C\\\@<!&varsubsetneq;_\&#x228a;\&#xfe00;_geI
  sm_\C\\\@<!&varsubsetneqq;_\&#x2acb;\&#xfe00;_geI
  sm_\C\\\@<!&varsupsetneq;_\&#x228b;\&#xfe00;_geI
  sm_\C\\\@<!&varsupsetneqq;_\&#x2acc;\&#xfe00;_geI
  sm_\C\\\@<!&vnsub;_\&#x2282;\&#x20d2;_geI
  sm_\C\\\@<!&vnsup;_\&#x2283;\&#x20d2;_geI
  sm_\C\\\@<!&vsubnE;_\&#x2acb;\&#xfe00;_geI
  sm_\C\\\@<!&vsubne;_\&#x228a;\&#xfe00;_geI
  sm_\C\\\@<!&vsupnE;_\&#x2acc;\&#xfe00;_geI
  sm_\C\\\@<!&vsupne;_\&#x228b;\&#xfe00;_geI
  sm_\C\\\@<!&nbsp;_\&#xa0;_geI
  sm_\C\\\@<!&iexcl;_\&#xa1;_geI
  sm_\C\\\@<!&cent;_\&#xa2;_geI
  sm_\C\\\@<!&pound;_\&#xa3;_geI
  sm_\C\\\@<!&curren;_\&#xa4;_geI
  sm_\C\\\@<!&yen;_\&#xa5;_geI
  sm_\C\\\@<!&brvbar;_\&#xa6;_geI
  sm_\C\\\@<!&sect;_\&#xa7;_geI
  sm_\C\\\@<!&uml;_\&#xa8;_geI
  sm_\C\\\@<!&copy;_\&#xa9;_geI
  sm_\C\\\@<!&ordf;_\&#xaa;_geI
  sm_\C\\\@<!&laquo;_\&#xab;_geI
  sm_\C\\\@<!&not;_\&#xac;_geI
  sm_\C\\\@<!&shy;_\&#xad;_geI
  sm_\C\\\@<!&reg;_\&#xae;_geI
  sm_\C\\\@<!&macr;_\&#xaf;_geI
  sm_\C\\\@<!&deg;_\&#xb0;_geI
  sm_\C\\\@<!&plusmn;_\&#xb1;_geI
  sm_\C\\\@<!&sup2;_\&#xb2;_geI
  sm_\C\\\@<!&sup3;_\&#xb3;_geI
  sm_\C\\\@<!&acute;_\&#xb4;_geI
  sm_\C\\\@<!&micro;_\&#xb5;_geI
  sm_\C\\\@<!&para;_\&#xb6;_geI
  sm_\C\\\@<!&middot;_\&#xb7;_geI
  sm_\C\\\@<!&cedil;_\&#xb8;_geI
  sm_\C\\\@<!&sup1;_\&#xb9;_geI
  sm_\C\\\@<!&ordm;_\&#xba;_geI
  sm_\C\\\@<!&raquo;_\&#xbb;_geI
  sm_\C\\\@<!&frac14;_\&#xbc;_geI
  sm_\C\\\@<!&frac12;_\&#xbd;_geI
  sm_\C\\\@<!&frac34;_\&#xbe;_geI
  sm_\C\\\@<!&iquest;_\&#xbf;_geI
  sm_\C\\\@<!&Agrave;_\&#xc0;_geI
  sm_\C\\\@<!&Aacute;_\&#xc1;_geI
  sm_\C\\\@<!&Acirc;_\&#xc2;_geI
  sm_\C\\\@<!&Atilde;_\&#xc3;_geI
  sm_\C\\\@<!&Auml;_\&#xc4;_geI
  sm_\C\\\@<!&Aring;_\&#xc5;_geI
  sm_\C\\\@<!&AElig;_\&#xc6;_geI
  sm_\C\\\@<!&Ccedil;_\&#xc7;_geI
  sm_\C\\\@<!&Egrave;_\&#xc8;_geI
  sm_\C\\\@<!&Eacute;_\&#xc9;_geI
  sm_\C\\\@<!&Ecirc;_\&#xca;_geI
  sm_\C\\\@<!&Euml;_\&#xcb;_geI
  sm_\C\\\@<!&Igrave;_\&#xcc;_geI
  sm_\C\\\@<!&Iacute;_\&#xcd;_geI
  sm_\C\\\@<!&Icirc;_\&#xce;_geI
  sm_\C\\\@<!&Iuml;_\&#xcf;_geI
  sm_\C\\\@<!&ETH;_\&#xd0;_geI
  sm_\C\\\@<!&Ntilde;_\&#xd1;_geI
  sm_\C\\\@<!&Ograve;_\&#xd2;_geI
  sm_\C\\\@<!&Oacute;_\&#xd3;_geI
  sm_\C\\\@<!&Ocirc;_\&#xd4;_geI
  sm_\C\\\@<!&Otilde;_\&#xd5;_geI
  sm_\C\\\@<!&Ouml;_\&#xd6;_geI
  sm_\C\\\@<!&times;_\&#xd7;_geI
  sm_\C\\\@<!&Oslash;_\&#xd8;_geI
  sm_\C\\\@<!&Ugrave;_\&#xd9;_geI
  sm_\C\\\@<!&Uacute;_\&#xda;_geI
  sm_\C\\\@<!&Ucirc;_\&#xdb;_geI
  sm_\C\\\@<!&Uuml;_\&#xdc;_geI
  sm_\C\\\@<!&Yacute;_\&#xdd;_geI
  sm_\C\\\@<!&THORN;_\&#xde;_geI
  sm_\C\\\@<!&szlig;_\&#xdf;_geI
  sm_\C\\\@<!&agrave;_\&#xe0;_geI
  sm_\C\\\@<!&aacute;_\&#xe1;_geI
  sm_\C\\\@<!&acirc;_\&#xe2;_geI
  sm_\C\\\@<!&atilde;_\&#xe3;_geI
  sm_\C\\\@<!&auml;_\&#xe4;_geI
  sm_\C\\\@<!&aring;_\&#xe5;_geI
  sm_\C\\\@<!&aelig;_\&#xe6;_geI
  sm_\C\\\@<!&ccedil;_\&#xe7;_geI
  sm_\C\\\@<!&egrave;_\&#xe8;_geI
  sm_\C\\\@<!&eacute;_\&#xe9;_geI
  sm_\C\\\@<!&ecirc;_\&#xea;_geI
  sm_\C\\\@<!&euml;_\&#xeb;_geI
  sm_\C\\\@<!&igrave;_\&#xec;_geI
  sm_\C\\\@<!&iacute;_\&#xed;_geI
  sm_\C\\\@<!&icirc;_\&#xee;_geI
  sm_\C\\\@<!&iuml;_\&#xef;_geI
  sm_\C\\\@<!&eth;_\&#xf0;_geI
  sm_\C\\\@<!&ntilde;_\&#xf1;_geI
  sm_\C\\\@<!&ograve;_\&#xf2;_geI
  sm_\C\\\@<!&oacute;_\&#xf3;_geI
  sm_\C\\\@<!&ocirc;_\&#xf4;_geI
  sm_\C\\\@<!&otilde;_\&#xf5;_geI
  sm_\C\\\@<!&ouml;_\&#xf6;_geI
  sm_\C\\\@<!&divide;_\&#xf7;_geI
  sm_\C\\\@<!&oslash;_\&#xf8;_geI
  sm_\C\\\@<!&ugrave;_\&#xf9;_geI
  sm_\C\\\@<!&uacute;_\&#xfa;_geI
  sm_\C\\\@<!&ucirc;_\&#xfb;_geI
  sm_\C\\\@<!&uuml;_\&#xfc;_geI
  sm_\C\\\@<!&yacute;_\&#xfd;_geI
  sm_\C\\\@<!&thorn;_\&#xfe;_geI
  sm_\C\\\@<!&yuml;_\&#xff;_geI
  if a:q=~'p'|sm_\C\\\@<!&quot;_\&#x22;_geI|endif
  if a:q=~'p'|sm_\C\\\@<!&amp;_\&#x26;_geI|endif
  if a:q=~'p'|sm_\C\\\@<!&lt;_\&#x3c;_geI|endif
  if a:q=~'p'|sm_\C\\\@<!&gt;_\&#x3e;_geI|endif
  if a:q=~'p'|sm_\C\\\@<!&apos;_\&#x27;_geI|endif
  sm_\C\\\@<!&OElig;_\&#x152;_geI
  sm_\C\\\@<!&oelig;_\&#x153;_geI
  sm_\C\\\@<!&Scaron;_\&#x160;_geI
  sm_\C\\\@<!&scaron;_\&#x161;_geI
  sm_\C\\\@<!&Yuml;_\&#x178;_geI
  sm_\C\\\@<!&circ;_\&#x2c6;_geI
  sm_\C\\\@<!&tilde;_\&#x2dc;_geI
  sm_\C\\\@<!&ensp;_\&#x2002;_geI
  sm_\C\\\@<!&emsp;_\&#x2003;_geI
  sm_\C\\\@<!&thinsp;_\&#x2009;_geI
  sm_\C\\\@<!&zwnj;_\&#x200c;_geI
  sm_\C\\\@<!&zwj;_\&#x200d;_geI
  sm_\C\\\@<!&lrm;_\&#x200e;_geI
  sm_\C\\\@<!&rlm;_\&#x200f;_geI
  sm_\C\\\@<!&ndash;_\&#x2013;_geI
  sm_\C\\\@<!&mdash;_\&#x2014;_geI
  sm_\C\\\@<!&lsquo;_\&#x2018;_geI
  sm_\C\\\@<!&rsquo;_\&#x2019;_geI
  sm_\C\\\@<!&sbquo;_\&#x201a;_geI
  sm_\C\\\@<!&ldquo;_\&#x201c;_geI
  sm_\C\\\@<!&rdquo;_\&#x201d;_geI
  sm_\C\\\@<!&bdquo;_\&#x201e;_geI
  sm_\C\\\@<!&dagger;_\&#x2020;_geI
  sm_\C\\\@<!&Dagger;_\&#x2021;_geI
  sm_\C\\\@<!&permil;_\&#x2030;_geI
  sm_\C\\\@<!&lsaquo;_\&#x2039;_geI
  sm_\C\\\@<!&rsaquo;_\&#x203a;_geI
  sm_\C\\\@<!&euro;_\&#x20ac;_geI
  sm_\C\\\@<!&fnof;_\&#x192;_geI
  sm_\C\\\@<!&Alpha;_\&#x391;_geI
  sm_\C\\\@<!&Beta;_\&#x392;_geI
  sm_\C\\\@<!&Gamma;_\&#x393;_geI
  sm_\C\\\@<!&Delta;_\&#x394;_geI
  sm_\C\\\@<!&Epsilon;_\&#x395;_geI
  sm_\C\\\@<!&Zeta;_\&#x396;_geI
  sm_\C\\\@<!&Eta;_\&#x397;_geI
  sm_\C\\\@<!&Theta;_\&#x398;_geI
  sm_\C\\\@<!&Iota;_\&#x399;_geI
  sm_\C\\\@<!&Kappa;_\&#x39a;_geI
  sm_\C\\\@<!&Lambda;_\&#x39b;_geI
  sm_\C\\\@<!&Mu;_\&#x39c;_geI
  sm_\C\\\@<!&Nu;_\&#x39d;_geI
  sm_\C\\\@<!&Xi;_\&#x39e;_geI
  sm_\C\\\@<!&Omicron;_\&#x39f;_geI
  sm_\C\\\@<!&Pi;_\&#x3a0;_geI
  sm_\C\\\@<!&Rho;_\&#x3a1;_geI
  sm_\C\\\@<!&Sigma;_\&#x3a3;_geI
  sm_\C\\\@<!&Tau;_\&#x3a4;_geI
  sm_\C\\\@<!&Upsilon;_\&#x3a5;_geI
  sm_\C\\\@<!&Phi;_\&#x3a6;_geI
  sm_\C\\\@<!&Chi;_\&#x3a7;_geI
  sm_\C\\\@<!&Psi;_\&#x3a8;_geI
  sm_\C\\\@<!&Omega;_\&#x3a9;_geI
  sm_\C\\\@<!&alpha;_\&#x3b1;_geI
  sm_\C\\\@<!&beta;_\&#x3b2;_geI
  sm_\C\\\@<!&gamma;_\&#x3b3;_geI
  sm_\C\\\@<!&delta;_\&#x3b4;_geI
  sm_\C\\\@<!&epsilon;_\&#x3b5;_geI
  sm_\C\\\@<!&zeta;_\&#x3b6;_geI
  sm_\C\\\@<!&eta;_\&#x3b7;_geI
  sm_\C\\\@<!&theta;_\&#x3b8;_geI
  sm_\C\\\@<!&iota;_\&#x3b9;_geI
  sm_\C\\\@<!&kappa;_\&#x3ba;_geI
  sm_\C\\\@<!&lambda;_\&#x3bb;_geI
  sm_\C\\\@<!&mu;_\&#x3bc;_geI
  sm_\C\\\@<!&nu;_\&#x3bd;_geI
  sm_\C\\\@<!&xi;_\&#x3be;_geI
  sm_\C\\\@<!&omicron;_\&#x3bf;_geI
  sm_\C\\\@<!&pi;_\&#x3c0;_geI
  sm_\C\\\@<!&rho;_\&#x3c1;_geI
  sm_\C\\\@<!&sigmaf;_\&#x3c2;_geI
  sm_\C\\\@<!&sigma;_\&#x3c3;_geI
  sm_\C\\\@<!&tau;_\&#x3c4;_geI
  sm_\C\\\@<!&upsilon;_\&#x3c5;_geI
  sm_\C\\\@<!&phi;_\&#x3c6;_geI
  sm_\C\\\@<!&chi;_\&#x3c7;_geI
  sm_\C\\\@<!&psi;_\&#x3c8;_geI
  sm_\C\\\@<!&omega;_\&#x3c9;_geI
  sm_\C\\\@<!&thetasym;_\&#x3d1;_geI
  sm_\C\\\@<!&upsih;_\&#x3d2;_geI
  sm_\C\\\@<!&piv;_\&#x3d6;_geI
  sm_\C\\\@<!&bull;_\&#x2022;_geI
  sm_\C\\\@<!&hellip;_\&#x2026;_geI
  sm_\C\\\@<!&prime;_\&#x2032;_geI
  sm_\C\\\@<!&Prime;_\&#x2033;_geI
  sm_\C\\\@<!&oline;_\&#x203e;_geI
  sm_\C\\\@<!&frasl;_\&#x2044;_geI
  sm_\C\\\@<!&weierp;_\&#x2118;_geI
  sm_\C\\\@<!&image;_\&#x2111;_geI
  sm_\C\\\@<!&real;_\&#x211c;_geI
  sm_\C\\\@<!&trade;_\&#x2122;_geI
  sm_\C\\\@<!&alefsym;_\&#x2135;_geI
  sm_\C\\\@<!&larr;_\&#x2190;_geI
  sm_\C\\\@<!&uarr;_\&#x2191;_geI
  sm_\C\\\@<!&rarr;_\&#x2192;_geI
  sm_\C\\\@<!&darr;_\&#x2193;_geI
  sm_\C\\\@<!&harr;_\&#x2194;_geI
  sm_\C\\\@<!&crarr;_\&#x21b5;_geI
  sm_\C\\\@<!&lArr;_\&#x21d0;_geI
  sm_\C\\\@<!&uArr;_\&#x21d1;_geI
  sm_\C\\\@<!&rArr;_\&#x21d2;_geI
  sm_\C\\\@<!&dArr;_\&#x21d3;_geI
  sm_\C\\\@<!&hArr;_\&#x21d4;_geI
  sm_\C\\\@<!&forall;_\&#x2200;_geI
  sm_\C\\\@<!&part;_\&#x2202;_geI
  sm_\C\\\@<!&exist;_\&#x2203;_geI
  sm_\C\\\@<!&empty;_\&#x2205;_geI
  sm_\C\\\@<!&nabla;_\&#x2207;_geI
  sm_\C\\\@<!&isin;_\&#x2208;_geI
  sm_\C\\\@<!&notin;_\&#x2209;_geI
  sm_\C\\\@<!&ni;_\&#x220b;_geI
  sm_\C\\\@<!&prod;_\&#x220f;_geI
  sm_\C\\\@<!&sum;_\&#x2211;_geI
  sm_\C\\\@<!&minus;_\&#x2212;_geI
  sm_\C\\\@<!&lowast;_\&#x2217;_geI
  sm_\C\\\@<!&radic;_\&#x221a;_geI
  sm_\C\\\@<!&prop;_\&#x221d;_geI
  sm_\C\\\@<!&infin;_\&#x221e;_geI
  sm_\C\\\@<!&ang;_\&#x2220;_geI
  sm_\C\\\@<!&and;_\&#x2227;_geI
  sm_\C\\\@<!&or;_\&#x2228;_geI
  sm_\C\\\@<!&cap;_\&#x2229;_geI
  sm_\C\\\@<!&cup;_\&#x222a;_geI
  sm_\C\\\@<!&int;_\&#x222b;_geI
  sm_\C\\\@<!&there4;_\&#x2234;_geI
  sm_\C\\\@<!&sim;_\&#x223c;_geI
  sm_\C\\\@<!&cong;_\&#x2245;_geI
  sm_\C\\\@<!&asymp;_\&#x2248;_geI
  sm_\C\\\@<!&ne;_\&#x2260;_geI
  sm_\C\\\@<!&equiv;_\&#x2261;_geI
  sm_\C\\\@<!&le;_\&#x2264;_geI
  sm_\C\\\@<!&ge;_\&#x2265;_geI
  sm_\C\\\@<!&sub;_\&#x2282;_geI
  sm_\C\\\@<!&sup;_\&#x2283;_geI
  sm_\C\\\@<!&nsub;_\&#x2284;_geI
  sm_\C\\\@<!&sube;_\&#x2286;_geI
  sm_\C\\\@<!&supe;_\&#x2287;_geI
  sm_\C\\\@<!&oplus;_\&#x2295;_geI
  sm_\C\\\@<!&otimes;_\&#x2297;_geI
  sm_\C\\\@<!&perp;_\&#x22a5;_geI
  sm_\C\\\@<!&sdot;_\&#x22c5;_geI
  sm_\C\\\@<!&lceil;_\&#x2308;_geI
  sm_\C\\\@<!&rceil;_\&#x2309;_geI
  sm_\C\\\@<!&lfloor;_\&#x230a;_geI
  sm_\C\\\@<!&rfloor;_\&#x230b;_geI
  sm_\C\\\@<!&lang;_\&#x2329;_geI
  sm_\C\\\@<!&rang;_\&#x232a;_geI
  sm_\C\\\@<!&loz;_\&#x25ca;_geI
  sm_\C\\\@<!&spades;_\&#x2660;_geI
  sm_\C\\\@<!&clubs;_\&#x2663;_geI
  sm_\C\\\@<!&hearts;_\&#x2665;_geI
  sm_\C\\\@<!&diams;_\&#x2666;_geI
  sm_\C\\\@<!&Abreve;_\&#x102;_geI
  sm_\C\\\@<!&abreve;_\&#x103;_geI
  sm_\C\\\@<!&ac;_\&#x223e;_geI
  sm_\C\\\@<!&acd;_\&#x223f;_geI
  sm_\C\\\@<!&Acy;_\&#x410;_geI
  sm_\C\\\@<!&acy;_\&#x430;_geI
  sm_\C\\\@<!&af;_\&#x2061;_geI
  sm_\C\\\@<!&Afr;_\&#x1d504;_geI
  sm_\C\\\@<!&afr;_\&#x1d51e;_geI
  sm_\C\\\@<!&aleph;_\&#x2135;_geI
  sm_\C\\\@<!&Amacr;_\&#x100;_geI
  sm_\C\\\@<!&amacr;_\&#x101;_geI
  sm_\C\\\@<!&amalg;_\&#x2a3f;_geI
  if a:q=~'s'|sm_\C\\\@<!&AMP;_\&#x26;_geI|endif
  sm_\C\\\@<!&And;_\&#x2a53;_geI
  sm_\C\\\@<!&andand;_\&#x2a55;_geI
  sm_\C\\\@<!&andd;_\&#x2a5c;_geI
  sm_\C\\\@<!&andslope;_\&#x2a58;_geI
  sm_\C\\\@<!&andv;_\&#x2a5a;_geI
  sm_\C\\\@<!&ange;_\&#x29a4;_geI
  sm_\C\\\@<!&angle;_\&#x2220;_geI
  sm_\C\\\@<!&angmsd;_\&#x2221;_geI
  sm_\C\\\@<!&angmsdaa;_\&#x29a8;_geI
  sm_\C\\\@<!&angmsdab;_\&#x29a9;_geI
  sm_\C\\\@<!&angmsdac;_\&#x29aa;_geI
  sm_\C\\\@<!&angmsdad;_\&#x29ab;_geI
  sm_\C\\\@<!&angmsdae;_\&#x29ac;_geI
  sm_\C\\\@<!&angmsdaf;_\&#x29ad;_geI
  sm_\C\\\@<!&angmsdag;_\&#x29ae;_geI
  sm_\C\\\@<!&angmsdah;_\&#x29af;_geI
  sm_\C\\\@<!&angrt;_\&#x221f;_geI
  sm_\C\\\@<!&angrtvb;_\&#x22be;_geI
  sm_\C\\\@<!&angrtvbd;_\&#x299d;_geI
  sm_\C\\\@<!&angsph;_\&#x2222;_geI
  sm_\C\\\@<!&angst;_\&#xc5;_geI
  sm_\C\\\@<!&angzarr;_\&#x237c;_geI
  sm_\C\\\@<!&Aogon;_\&#x104;_geI
  sm_\C\\\@<!&aogon;_\&#x105;_geI
  sm_\C\\\@<!&Aopf;_\&#x1d538;_geI
  sm_\C\\\@<!&aopf;_\&#x1d552;_geI
  sm_\C\\\@<!&ap;_\&#x2248;_geI
  sm_\C\\\@<!&apacir;_\&#x2a6f;_geI
  sm_\C\\\@<!&apE;_\&#x2a70;_geI
  sm_\C\\\@<!&ape;_\&#x224a;_geI
  sm_\C\\\@<!&apid;_\&#x224b;_geI
  sm_\C\\\@<!&ApplyFunction;_\&#x2061;_geI
  sm_\C\\\@<!&approx;_\&#x2248;_geI
  sm_\C\\\@<!&approxeq;_\&#x224a;_geI
  sm_\C\\\@<!&Ascr;_\&#x1d49c;_geI
  sm_\C\\\@<!&ascr;_\&#x1d4b6;_geI
  sm_\C\\\@<!&Assign;_\&#x2254;_geI
  if a:q=~'s'|sm_\C\\\@<!&ast;_\&#x2a;_geI|endif
  sm_\C\\\@<!&asympeq;_\&#x224d;_geI
  sm_\C\\\@<!&awconint;_\&#x2233;_geI
  sm_\C\\\@<!&awint;_\&#x2a11;_geI
  sm_\C\\\@<!&backcong;_\&#x224c;_geI
  sm_\C\\\@<!&backepsilon;_\&#x3f6;_geI
  sm_\C\\\@<!&backprime;_\&#x2035;_geI
  sm_\C\\\@<!&backsim;_\&#x223d;_geI
  sm_\C\\\@<!&backsimeq;_\&#x22cd;_geI
  sm_\C\\\@<!&Backslash;_\&#x2216;_geI
  sm_\C\\\@<!&Barv;_\&#x2ae7;_geI
  sm_\C\\\@<!&barvee;_\&#x22bd;_geI
  sm_\C\\\@<!&Barwed;_\&#x2306;_geI
  sm_\C\\\@<!&barwed;_\&#x2305;_geI
  sm_\C\\\@<!&barwedge;_\&#x2305;_geI
  sm_\C\\\@<!&bbrk;_\&#x23b5;_geI
  sm_\C\\\@<!&bbrktbrk;_\&#x23b6;_geI
  sm_\C\\\@<!&bcong;_\&#x224c;_geI
  sm_\C\\\@<!&Bcy;_\&#x411;_geI
  sm_\C\\\@<!&bcy;_\&#x431;_geI
  sm_\C\\\@<!&becaus;_\&#x2235;_geI
  sm_\C\\\@<!&Because;_\&#x2235;_geI
  sm_\C\\\@<!&because;_\&#x2235;_geI
  sm_\C\\\@<!&bemptyv;_\&#x29b0;_geI
  sm_\C\\\@<!&bepsi;_\&#x3f6;_geI
  sm_\C\\\@<!&bernou;_\&#x212c;_geI
  sm_\C\\\@<!&Bernoullis;_\&#x212c;_geI
  sm_\C\\\@<!&beth;_\&#x2136;_geI
  sm_\C\\\@<!&between;_\&#x226c;_geI
  sm_\C\\\@<!&Bfr;_\&#x1d505;_geI
  sm_\C\\\@<!&bfr;_\&#x1d51f;_geI
  sm_\C\\\@<!&bigcap;_\&#x22c2;_geI
  sm_\C\\\@<!&bigcirc;_\&#x25ef;_geI
  sm_\C\\\@<!&bigcup;_\&#x22c3;_geI
  sm_\C\\\@<!&bigodot;_\&#x2a00;_geI
  sm_\C\\\@<!&bigoplus;_\&#x2a01;_geI
  sm_\C\\\@<!&bigotimes;_\&#x2a02;_geI
  sm_\C\\\@<!&bigsqcup;_\&#x2a06;_geI
  sm_\C\\\@<!&bigstar;_\&#x2605;_geI
  sm_\C\\\@<!&bigtriangledown;_\&#x25bd;_geI
  sm_\C\\\@<!&bigtriangleup;_\&#x25b3;_geI
  sm_\C\\\@<!&biguplus;_\&#x2a04;_geI
  sm_\C\\\@<!&bigvee;_\&#x22c1;_geI
  sm_\C\\\@<!&bigwedge;_\&#x22c0;_geI
  sm_\C\\\@<!&bkarow;_\&#x290d;_geI
  sm_\C\\\@<!&blacklozenge;_\&#x29eb;_geI
  sm_\C\\\@<!&blacksquare;_\&#x25aa;_geI
  sm_\C\\\@<!&blacktriangle;_\&#x25b4;_geI
  sm_\C\\\@<!&blacktriangledown;_\&#x25be;_geI
  sm_\C\\\@<!&blacktriangleleft;_\&#x25c2;_geI
  sm_\C\\\@<!&blacktriangleright;_\&#x25b8;_geI
  sm_\C\\\@<!&blank;_\&#x2423;_geI
  sm_\C\\\@<!&blk12;_\&#x2592;_geI
  sm_\C\\\@<!&blk14;_\&#x2591;_geI
  sm_\C\\\@<!&blk34;_\&#x2593;_geI
  sm_\C\\\@<!&block;_\&#x2588;_geI
  sm_\C\\\@<!&bNot;_\&#x2aed;_geI
  sm_\C\\\@<!&bnot;_\&#x2310;_geI
  sm_\C\\\@<!&Bopf;_\&#x1d539;_geI
  sm_\C\\\@<!&bopf;_\&#x1d553;_geI
  sm_\C\\\@<!&bot;_\&#x22a5;_geI
  sm_\C\\\@<!&bottom;_\&#x22a5;_geI
  sm_\C\\\@<!&bowtie;_\&#x22c8;_geI
  sm_\C\\\@<!&boxbox;_\&#x29c9;_geI
  sm_\C\\\@<!&boxDL;_\&#x2557;_geI
  sm_\C\\\@<!&boxDl;_\&#x2556;_geI
  sm_\C\\\@<!&boxdL;_\&#x2555;_geI
  sm_\C\\\@<!&boxdl;_\&#x2510;_geI
  sm_\C\\\@<!&boxDR;_\&#x2554;_geI
  sm_\C\\\@<!&boxDr;_\&#x2553;_geI
  sm_\C\\\@<!&boxdR;_\&#x2552;_geI
  sm_\C\\\@<!&boxdr;_\&#x250c;_geI
  sm_\C\\\@<!&boxH;_\&#x2550;_geI
  sm_\C\\\@<!&boxh;_\&#x2500;_geI
  sm_\C\\\@<!&boxHD;_\&#x2566;_geI
  sm_\C\\\@<!&boxHd;_\&#x2564;_geI
  sm_\C\\\@<!&boxhD;_\&#x2565;_geI
  sm_\C\\\@<!&boxhd;_\&#x252c;_geI
  sm_\C\\\@<!&boxHU;_\&#x2569;_geI
  sm_\C\\\@<!&boxHu;_\&#x2567;_geI
  sm_\C\\\@<!&boxhU;_\&#x2568;_geI
  sm_\C\\\@<!&boxhu;_\&#x2534;_geI
  sm_\C\\\@<!&boxminus;_\&#x229f;_geI
  sm_\C\\\@<!&boxplus;_\&#x229e;_geI
  sm_\C\\\@<!&boxtimes;_\&#x22a0;_geI
  sm_\C\\\@<!&boxUL;_\&#x255d;_geI
  sm_\C\\\@<!&boxUl;_\&#x255c;_geI
  sm_\C\\\@<!&boxuL;_\&#x255b;_geI
  sm_\C\\\@<!&boxul;_\&#x2518;_geI
  sm_\C\\\@<!&boxUR;_\&#x255a;_geI
  sm_\C\\\@<!&boxUr;_\&#x2559;_geI
  sm_\C\\\@<!&boxuR;_\&#x2558;_geI
  sm_\C\\\@<!&boxur;_\&#x2514;_geI
  sm_\C\\\@<!&boxV;_\&#x2551;_geI
  sm_\C\\\@<!&boxv;_\&#x2502;_geI
  sm_\C\\\@<!&boxVH;_\&#x256c;_geI
  sm_\C\\\@<!&boxVh;_\&#x256b;_geI
  sm_\C\\\@<!&boxvH;_\&#x256a;_geI
  sm_\C\\\@<!&boxvh;_\&#x253c;_geI
  sm_\C\\\@<!&boxVL;_\&#x2563;_geI
  sm_\C\\\@<!&boxVl;_\&#x2562;_geI
  sm_\C\\\@<!&boxvL;_\&#x2561;_geI
  sm_\C\\\@<!&boxvl;_\&#x2524;_geI
  sm_\C\\\@<!&boxVR;_\&#x2560;_geI
  sm_\C\\\@<!&boxVr;_\&#x255f;_geI
  sm_\C\\\@<!&boxvR;_\&#x255e;_geI
  sm_\C\\\@<!&boxvr;_\&#x251c;_geI
  sm_\C\\\@<!&bprime;_\&#x2035;_geI
  sm_\C\\\@<!&Breve;_\&#x2d8;_geI
  sm_\C\\\@<!&breve;_\&#x2d8;_geI
  sm_\C\\\@<!&Bscr;_\&#x212c;_geI
  sm_\C\\\@<!&bscr;_\&#x1d4b7;_geI
  sm_\C\\\@<!&bsemi;_\&#x204f;_geI
  sm_\C\\\@<!&bsim;_\&#x223d;_geI
  sm_\C\\\@<!&bsime;_\&#x22cd;_geI
  if a:q=~'s'|sm_\C\\\@<!&bsol;_\&#x5c;_geI|endif
  sm_\C\\\@<!&bsolb;_\&#x29c5;_geI
  sm_\C\\\@<!&bsolhsub;_\&#x27c8;_geI
  sm_\C\\\@<!&bullet;_\&#x2022;_geI
  sm_\C\\\@<!&bump;_\&#x224e;_geI
  sm_\C\\\@<!&bumpE;_\&#x2aae;_geI
  sm_\C\\\@<!&bumpe;_\&#x224f;_geI
  sm_\C\\\@<!&Bumpeq;_\&#x224e;_geI
  sm_\C\\\@<!&bumpeq;_\&#x224f;_geI
  sm_\C\\\@<!&Cacute;_\&#x106;_geI
  sm_\C\\\@<!&cacute;_\&#x107;_geI
  sm_\C\\\@<!&Cap;_\&#x22d2;_geI
  sm_\C\\\@<!&capand;_\&#x2a44;_geI
  sm_\C\\\@<!&capbrcup;_\&#x2a49;_geI
  sm_\C\\\@<!&capcap;_\&#x2a4b;_geI
  sm_\C\\\@<!&capcup;_\&#x2a47;_geI
  sm_\C\\\@<!&capdot;_\&#x2a40;_geI
  sm_\C\\\@<!&CapitalDifferentialD;_\&#x2145;_geI
  sm_\C\\\@<!&caret;_\&#x2041;_geI
  sm_\C\\\@<!&caron;_\&#x2c7;_geI
  sm_\C\\\@<!&Cayleys;_\&#x212d;_geI
  sm_\C\\\@<!&ccaps;_\&#x2a4d;_geI
  sm_\C\\\@<!&Ccaron;_\&#x10c;_geI
  sm_\C\\\@<!&ccaron;_\&#x10d;_geI
  sm_\C\\\@<!&Ccirc;_\&#x108;_geI
  sm_\C\\\@<!&ccirc;_\&#x109;_geI
  sm_\C\\\@<!&Cconint;_\&#x2230;_geI
  sm_\C\\\@<!&ccups;_\&#x2a4c;_geI
  sm_\C\\\@<!&ccupssm;_\&#x2a50;_geI
  sm_\C\\\@<!&Cdot;_\&#x10a;_geI
  sm_\C\\\@<!&cdot;_\&#x10b;_geI
  sm_\C\\\@<!&Cedilla;_\&#xb8;_geI
  sm_\C\\\@<!&cemptyv;_\&#x29b2;_geI
  sm_\C\\\@<!&CenterDot;_\&#xb7;_geI
  sm_\C\\\@<!&centerdot;_\&#xb7;_geI
  sm_\C\\\@<!&Cfr;_\&#x212d;_geI
  sm_\C\\\@<!&cfr;_\&#x1d520;_geI
  sm_\C\\\@<!&CHcy;_\&#x427;_geI
  sm_\C\\\@<!&chcy;_\&#x447;_geI
  sm_\C\\\@<!&check;_\&#x2713;_geI
  sm_\C\\\@<!&checkmark;_\&#x2713;_geI
  sm_\C\\\@<!&cir;_\&#x25cb;_geI
  sm_\C\\\@<!&circeq;_\&#x2257;_geI
  sm_\C\\\@<!&circlearrowleft;_\&#x21ba;_geI
  sm_\C\\\@<!&circlearrowright;_\&#x21bb;_geI
  sm_\C\\\@<!&circledast;_\&#x229b;_geI
  sm_\C\\\@<!&circledcirc;_\&#x229a;_geI
  sm_\C\\\@<!&circleddash;_\&#x229d;_geI
  sm_\C\\\@<!&CircleDot;_\&#x2299;_geI
  sm_\C\\\@<!&circledR;_\&#xae;_geI
  sm_\C\\\@<!&circledS;_\&#x24c8;_geI
  sm_\C\\\@<!&CircleMinus;_\&#x2296;_geI
  sm_\C\\\@<!&CirclePlus;_\&#x2295;_geI
  sm_\C\\\@<!&CircleTimes;_\&#x2297;_geI
  sm_\C\\\@<!&cirE;_\&#x29c3;_geI
  sm_\C\\\@<!&cire;_\&#x2257;_geI
  sm_\C\\\@<!&cirfnint;_\&#x2a10;_geI
  sm_\C\\\@<!&cirmid;_\&#x2aef;_geI
  sm_\C\\\@<!&cirscir;_\&#x29c2;_geI
  sm_\C\\\@<!&ClockwiseContourIntegral;_\&#x2232;_geI
  sm_\C\\\@<!&CloseCurlyDoubleQuote;_\&#x201d;_geI
  sm_\C\\\@<!&CloseCurlyQuote;_\&#x2019;_geI
  sm_\C\\\@<!&clubsuit;_\&#x2663;_geI
  sm_\C\\\@<!&Colon;_\&#x2237;_geI
  if a:q=~'s'|sm_\C\\\@<!&colon;_\&#x3a;_geI|endif
  sm_\C\\\@<!&Colone;_\&#x2a74;_geI
  sm_\C\\\@<!&colone;_\&#x2254;_geI
  sm_\C\\\@<!&coloneq;_\&#x2254;_geI
  if a:q=~'s'|sm_\C\\\@<!&comma;_\&#x2c;_geI|endif
  if a:q=~'s'|sm_\C\\\@<!&commat;_\&#x40;_geI|endif
  sm_\C\\\@<!&comp;_\&#x2201;_geI
  sm_\C\\\@<!&compfn;_\&#x2218;_geI
  sm_\C\\\@<!&complement;_\&#x2201;_geI
  sm_\C\\\@<!&complexes;_\&#x2102;_geI
  sm_\C\\\@<!&congdot;_\&#x2a6d;_geI
  sm_\C\\\@<!&Congruent;_\&#x2261;_geI
  sm_\C\\\@<!&Conint;_\&#x222f;_geI
  sm_\C\\\@<!&conint;_\&#x222e;_geI
  sm_\C\\\@<!&ContourIntegral;_\&#x222e;_geI
  sm_\C\\\@<!&Copf;_\&#x2102;_geI
  sm_\C\\\@<!&copf;_\&#x1d554;_geI
  sm_\C\\\@<!&coprod;_\&#x2210;_geI
  sm_\C\\\@<!&Coproduct;_\&#x2210;_geI
  sm_\C\\\@<!&COPY;_\&#xa9;_geI
  sm_\C\\\@<!&copysr;_\&#x2117;_geI
  sm_\C\\\@<!&CounterClockwiseContourIntegral;_\&#x2233;_geI
  sm_\C\\\@<!&Cross;_\&#x2a2f;_geI
  sm_\C\\\@<!&cross;_\&#x2717;_geI
  sm_\C\\\@<!&Cscr;_\&#x1d49e;_geI
  sm_\C\\\@<!&cscr;_\&#x1d4b8;_geI
  sm_\C\\\@<!&csub;_\&#x2acf;_geI
  sm_\C\\\@<!&csube;_\&#x2ad1;_geI
  sm_\C\\\@<!&csup;_\&#x2ad0;_geI
  sm_\C\\\@<!&csupe;_\&#x2ad2;_geI
  sm_\C\\\@<!&ctdot;_\&#x22ef;_geI
  sm_\C\\\@<!&cudarrl;_\&#x2938;_geI
  sm_\C\\\@<!&cudarrr;_\&#x2935;_geI
  sm_\C\\\@<!&cuepr;_\&#x22de;_geI
  sm_\C\\\@<!&cuesc;_\&#x22df;_geI
  sm_\C\\\@<!&cularr;_\&#x21b6;_geI
  sm_\C\\\@<!&cularrp;_\&#x293d;_geI
  sm_\C\\\@<!&Cup;_\&#x22d3;_geI
  sm_\C\\\@<!&cupbrcap;_\&#x2a48;_geI
  sm_\C\\\@<!&CupCap;_\&#x224d;_geI
  sm_\C\\\@<!&cupcap;_\&#x2a46;_geI
  sm_\C\\\@<!&cupcup;_\&#x2a4a;_geI
  sm_\C\\\@<!&cupdot;_\&#x228d;_geI
  sm_\C\\\@<!&cupor;_\&#x2a45;_geI
  sm_\C\\\@<!&curarr;_\&#x21b7;_geI
  sm_\C\\\@<!&curarrm;_\&#x293c;_geI
  sm_\C\\\@<!&curlyeqprec;_\&#x22de;_geI
  sm_\C\\\@<!&curlyeqsucc;_\&#x22df;_geI
  sm_\C\\\@<!&curlyvee;_\&#x22ce;_geI
  sm_\C\\\@<!&curlywedge;_\&#x22cf;_geI
  sm_\C\\\@<!&curvearrowleft;_\&#x21b6;_geI
  sm_\C\\\@<!&curvearrowright;_\&#x21b7;_geI
  sm_\C\\\@<!&cuvee;_\&#x22ce;_geI
  sm_\C\\\@<!&cuwed;_\&#x22cf;_geI
  sm_\C\\\@<!&cwconint;_\&#x2232;_geI
  sm_\C\\\@<!&cwint;_\&#x2231;_geI
  sm_\C\\\@<!&cylcty;_\&#x232d;_geI
  sm_\C\\\@<!&daleth;_\&#x2138;_geI
  sm_\C\\\@<!&Darr;_\&#x21a1;_geI
  sm_\C\\\@<!&dash;_\&#x2010;_geI
  sm_\C\\\@<!&Dashv;_\&#x2ae4;_geI
  sm_\C\\\@<!&dashv;_\&#x22a3;_geI
  sm_\C\\\@<!&dbkarow;_\&#x290f;_geI
  sm_\C\\\@<!&dblac;_\&#x2dd;_geI
  sm_\C\\\@<!&Dcaron;_\&#x10e;_geI
  sm_\C\\\@<!&dcaron;_\&#x10f;_geI
  sm_\C\\\@<!&Dcy;_\&#x414;_geI
  sm_\C\\\@<!&dcy;_\&#x434;_geI
  sm_\C\\\@<!&DD;_\&#x2145;_geI
  sm_\C\\\@<!&dd;_\&#x2146;_geI
  sm_\C\\\@<!&ddagger;_\&#x2021;_geI
  sm_\C\\\@<!&ddarr;_\&#x21ca;_geI
  sm_\C\\\@<!&DDotrahd;_\&#x2911;_geI
  sm_\C\\\@<!&ddotseq;_\&#x2a77;_geI
  sm_\C\\\@<!&Del;_\&#x2207;_geI
  sm_\C\\\@<!&demptyv;_\&#x29b1;_geI
  sm_\C\\\@<!&dfisht;_\&#x297f;_geI
  sm_\C\\\@<!&Dfr;_\&#x1d507;_geI
  sm_\C\\\@<!&dfr;_\&#x1d521;_geI
  sm_\C\\\@<!&dHar;_\&#x2965;_geI
  sm_\C\\\@<!&dharl;_\&#x21c3;_geI
  sm_\C\\\@<!&dharr;_\&#x21c2;_geI
  sm_\C\\\@<!&DiacriticalAcute;_\&#xb4;_geI
  sm_\C\\\@<!&DiacriticalDot;_\&#x2d9;_geI
  sm_\C\\\@<!&DiacriticalDoubleAcute;_\&#x2dd;_geI
  if a:q=~'s'|sm_\C\\\@<!&DiacriticalGrave;_\&#x60;_geI|endif
  sm_\C\\\@<!&DiacriticalTilde;_\&#x2dc;_geI
  sm_\C\\\@<!&diam;_\&#x22c4;_geI
  sm_\C\\\@<!&Diamond;_\&#x22c4;_geI
  sm_\C\\\@<!&diamond;_\&#x22c4;_geI
  sm_\C\\\@<!&diamondsuit;_\&#x2666;_geI
  sm_\C\\\@<!&die;_\&#xa8;_geI
  sm_\C\\\@<!&DifferentialD;_\&#x2146;_geI
  sm_\C\\\@<!&digamma;_\&#x3dd;_geI
  sm_\C\\\@<!&disin;_\&#x22f2;_geI
  sm_\C\\\@<!&div;_\&#xf7;_geI
  sm_\C\\\@<!&divideontimes;_\&#x22c7;_geI
  sm_\C\\\@<!&divonx;_\&#x22c7;_geI
  sm_\C\\\@<!&DJcy;_\&#x402;_geI
  sm_\C\\\@<!&djcy;_\&#x452;_geI
  sm_\C\\\@<!&dlcorn;_\&#x231e;_geI
  sm_\C\\\@<!&dlcrop;_\&#x230d;_geI
  if a:q=~'s'|sm_\C\\\@<!&dollar;_\&#x24;_geI|endif
  sm_\C\\\@<!&Dopf;_\&#x1d53b;_geI
  sm_\C\\\@<!&dopf;_\&#x1d555;_geI
  sm_\C\\\@<!&Dot;_\&#xa8;_geI
  sm_\C\\\@<!&dot;_\&#x2d9;_geI
  sm_\C\\\@<!&DotDot;_\&#x20dc;_geI
  sm_\C\\\@<!&doteq;_\&#x2250;_geI
  sm_\C\\\@<!&doteqdot;_\&#x2251;_geI
  sm_\C\\\@<!&DotEqual;_\&#x2250;_geI
  sm_\C\\\@<!&dotminus;_\&#x2238;_geI
  sm_\C\\\@<!&dotplus;_\&#x2214;_geI
  sm_\C\\\@<!&dotsquare;_\&#x22a1;_geI
  sm_\C\\\@<!&doublebarwedge;_\&#x2306;_geI
  sm_\C\\\@<!&DoubleContourIntegral;_\&#x222f;_geI
  sm_\C\\\@<!&DoubleDot;_\&#xa8;_geI
  sm_\C\\\@<!&DoubleDownArrow;_\&#x21d3;_geI
  sm_\C\\\@<!&DoubleLeftArrow;_\&#x21d0;_geI
  sm_\C\\\@<!&DoubleLeftRightArrow;_\&#x21d4;_geI
  sm_\C\\\@<!&DoubleLeftTee;_\&#x2ae4;_geI
  sm_\C\\\@<!&DoubleLongLeftArrow;_\&#x27f8;_geI
  sm_\C\\\@<!&DoubleLongLeftRightArrow;_\&#x27fa;_geI
  sm_\C\\\@<!&DoubleLongRightArrow;_\&#x27f9;_geI
  sm_\C\\\@<!&DoubleRightArrow;_\&#x21d2;_geI
  sm_\C\\\@<!&DoubleRightTee;_\&#x22a8;_geI
  sm_\C\\\@<!&DoubleUpArrow;_\&#x21d1;_geI
  sm_\C\\\@<!&DoubleUpDownArrow;_\&#x21d5;_geI
  sm_\C\\\@<!&DoubleVerticalBar;_\&#x2225;_geI
  sm_\C\\\@<!&DownArrow;_\&#x2193;_geI
  sm_\C\\\@<!&Downarrow;_\&#x21d3;_geI
  sm_\C\\\@<!&downarrow;_\&#x2193;_geI
  sm_\C\\\@<!&DownArrowBar;_\&#x2913;_geI
  sm_\C\\\@<!&DownArrowUpArrow;_\&#x21f5;_geI
  sm_\C\\\@<!&DownBreve;_\&#x311;_geI
  sm_\C\\\@<!&downdownarrows;_\&#x21ca;_geI
  sm_\C\\\@<!&downharpoonleft;_\&#x21c3;_geI
  sm_\C\\\@<!&downharpoonright;_\&#x21c2;_geI
  sm_\C\\\@<!&DownLeftRightVector;_\&#x2950;_geI
  sm_\C\\\@<!&DownLeftTeeVector;_\&#x295e;_geI
  sm_\C\\\@<!&DownLeftVector;_\&#x21bd;_geI
  sm_\C\\\@<!&DownLeftVectorBar;_\&#x2956;_geI
  sm_\C\\\@<!&DownRightTeeVector;_\&#x295f;_geI
  sm_\C\\\@<!&DownRightVector;_\&#x21c1;_geI
  sm_\C\\\@<!&DownRightVectorBar;_\&#x2957;_geI
  sm_\C\\\@<!&DownTee;_\&#x22a4;_geI
  sm_\C\\\@<!&DownTeeArrow;_\&#x21a7;_geI
  sm_\C\\\@<!&drbkarow;_\&#x2910;_geI
  sm_\C\\\@<!&drcorn;_\&#x231f;_geI
  sm_\C\\\@<!&drcrop;_\&#x230c;_geI
  sm_\C\\\@<!&Dscr;_\&#x1d49f;_geI
  sm_\C\\\@<!&dscr;_\&#x1d4b9;_geI
  sm_\C\\\@<!&DScy;_\&#x405;_geI
  sm_\C\\\@<!&dscy;_\&#x455;_geI
  sm_\C\\\@<!&dsol;_\&#x29f6;_geI
  sm_\C\\\@<!&Dstrok;_\&#x110;_geI
  sm_\C\\\@<!&dstrok;_\&#x111;_geI
  sm_\C\\\@<!&dtdot;_\&#x22f1;_geI
  sm_\C\\\@<!&dtri;_\&#x25bf;_geI
  sm_\C\\\@<!&dtrif;_\&#x25be;_geI
  sm_\C\\\@<!&duarr;_\&#x21f5;_geI
  sm_\C\\\@<!&duhar;_\&#x296f;_geI
  sm_\C\\\@<!&dwangle;_\&#x29a6;_geI
  sm_\C\\\@<!&DZcy;_\&#x40f;_geI
  sm_\C\\\@<!&dzcy;_\&#x45f;_geI
  sm_\C\\\@<!&dzigrarr;_\&#x27ff;_geI
  sm_\C\\\@<!&easter;_\&#x2a6e;_geI
  sm_\C\\\@<!&Ecaron;_\&#x11a;_geI
  sm_\C\\\@<!&ecaron;_\&#x11b;_geI
  sm_\C\\\@<!&ecir;_\&#x2256;_geI
  sm_\C\\\@<!&ecolon;_\&#x2255;_geI
  sm_\C\\\@<!&Ecy;_\&#x42d;_geI
  sm_\C\\\@<!&ecy;_\&#x44d;_geI
  sm_\C\\\@<!&eDDot;_\&#x2a77;_geI
  sm_\C\\\@<!&Edot;_\&#x116;_geI
  sm_\C\\\@<!&eDot;_\&#x2251;_geI
  sm_\C\\\@<!&edot;_\&#x117;_geI
  sm_\C\\\@<!&ee;_\&#x2147;_geI
  sm_\C\\\@<!&efDot;_\&#x2252;_geI
  sm_\C\\\@<!&Efr;_\&#x1d508;_geI
  sm_\C\\\@<!&efr;_\&#x1d522;_geI
  sm_\C\\\@<!&eg;_\&#x2a9a;_geI
  sm_\C\\\@<!&egs;_\&#x2a96;_geI
  sm_\C\\\@<!&egsdot;_\&#x2a98;_geI
  sm_\C\\\@<!&el;_\&#x2a99;_geI
  sm_\C\\\@<!&Element;_\&#x2208;_geI
  sm_\C\\\@<!&elinters;_\&#x230000000;_geI
  sm_\C\\\@<!&ell;_\&#x2113;_geI
  sm_\C\\\@<!&els;_\&#x2a95;_geI
  sm_\C\\\@<!&elsdot;_\&#x2a97;_geI
  sm_\C\\\@<!&Emacr;_\&#x112;_geI
  sm_\C\\\@<!&emacr;_\&#x113;_geI
  sm_\C\\\@<!&emptyset;_\&#x2205;_geI
  sm_\C\\\@<!&EmptySmallSquare;_\&#x25fb;_geI
  sm_\C\\\@<!&emptyv;_\&#x2205;_geI
  sm_\C\\\@<!&EmptyVerySmallSquare;_\&#x25ab;_geI
  sm_\C\\\@<!&emsp13;_\&#x2004;_geI
  sm_\C\\\@<!&emsp14;_\&#x2005;_geI
  sm_\C\\\@<!&ENG;_\&#x14a;_geI
  sm_\C\\\@<!&eng;_\&#x14b;_geI
  sm_\C\\\@<!&Eogon;_\&#x118;_geI
  sm_\C\\\@<!&eogon;_\&#x119;_geI
  sm_\C\\\@<!&Eopf;_\&#x1d53c;_geI
  sm_\C\\\@<!&eopf;_\&#x1d556;_geI
  sm_\C\\\@<!&epar;_\&#x22d5;_geI
  sm_\C\\\@<!&eparsl;_\&#x29000;_geI
  sm_\C\\\@<!&eplus;_\&#x2a71;_geI
  sm_\C\\\@<!&epsi;_\&#x3b5;_geI
  sm_\C\\\@<!&epsiv;_\&#x3f5;_geI
  sm_\C\\\@<!&eqcirc;_\&#x2256;_geI
  sm_\C\\\@<!&eqcolon;_\&#x2255;_geI
  sm_\C\\\@<!&eqsim;_\&#x2242;_geI
  sm_\C\\\@<!&eqslantgtr;_\&#x2a96;_geI
  sm_\C\\\@<!&eqslantless;_\&#x2a95;_geI
  sm_\C\\\@<!&Equal;_\&#x2a75;_geI
  if a:q=~'s'|sm_\C\\\@<!&equals;_\&#x3d;_geI|endif
  sm_\C\\\@<!&EqualTilde;_\&#x2242;_geI
  sm_\C\\\@<!&equest;_\&#x225f;_geI
  sm_\C\\\@<!&Equilibrium;_\&#x21cc;_geI
  sm_\C\\\@<!&equivDD;_\&#x2a78;_geI
  sm_\C\\\@<!&eqvparsl;_\&#x2900000;_geI
  sm_\C\\\@<!&erarr;_\&#x2971;_geI
  sm_\C\\\@<!&erDot;_\&#x2253;_geI
  sm_\C\\\@<!&Escr;_\&#x2130;_geI
  sm_\C\\\@<!&escr;_\&#x212f;_geI
  sm_\C\\\@<!&esdot;_\&#x2250;_geI
  sm_\C\\\@<!&Esim;_\&#x2a73;_geI
  sm_\C\\\@<!&esim;_\&#x2242;_geI
  if a:q=~'s'|sm_\C\\\@<!&excl;_\&#x21;_geI|endif
  sm_\C\\\@<!&Exists;_\&#x2203;_geI
  sm_\C\\\@<!&expectation;_\&#x2130;_geI
  sm_\C\\\@<!&ExponentialE;_\&#x2147;_geI
  sm_\C\\\@<!&exponentiale;_\&#x2147;_geI
  sm_\C\\\@<!&fallingdotseq;_\&#x2252;_geI
  sm_\C\\\@<!&Fcy;_\&#x424;_geI
  sm_\C\\\@<!&fcy;_\&#x444;_geI
  sm_\C\\\@<!&female;_\&#x2640;_geI
  sm_\C\\\@<!&ffilig;_\&#xfb03;_geI
  sm_\C\\\@<!&fflig;_\&#xfb00;_geI
  sm_\C\\\@<!&ffllig;_\&#xfb04;_geI
  sm_\C\\\@<!&Ffr;_\&#x1d509;_geI
  sm_\C\\\@<!&ffr;_\&#x1d523;_geI
  sm_\C\\\@<!&filig;_\&#xfb01;_geI
  sm_\C\\\@<!&FilledSmallSquare;_\&#x25fc;_geI
  sm_\C\\\@<!&FilledVerySmallSquare;_\&#x25aa;_geI
  sm_\C\\\@<!&flat;_\&#x266d;_geI
  sm_\C\\\@<!&fllig;_\&#xfb02;_geI
  sm_\C\\\@<!&fltns;_\&#x25b1;_geI
  sm_\C\\\@<!&Fopf;_\&#x1d53d;_geI
  sm_\C\\\@<!&fopf;_\&#x1d557;_geI
  sm_\C\\\@<!&ForAll;_\&#x2200;_geI
  sm_\C\\\@<!&fork;_\&#x22d4;_geI
  sm_\C\\\@<!&forkv;_\&#x2ad9;_geI
  sm_\C\\\@<!&Fouriertrf;_\&#x2131;_geI
  sm_\C\\\@<!&fpartint;_\&#x2a0d;_geI
  sm_\C\\\@<!&frac13;_\&#x2153;_geI
  sm_\C\\\@<!&frac15;_\&#x2155;_geI
  sm_\C\\\@<!&frac16;_\&#x2159;_geI
  sm_\C\\\@<!&frac18;_\&#x215b;_geI
  sm_\C\\\@<!&frac23;_\&#x2154;_geI
  sm_\C\\\@<!&frac25;_\&#x2156;_geI
  sm_\C\\\@<!&frac35;_\&#x2157;_geI
  sm_\C\\\@<!&frac38;_\&#x215c;_geI
  sm_\C\\\@<!&frac45;_\&#x2158;_geI
  sm_\C\\\@<!&frac56;_\&#x215a;_geI
  sm_\C\\\@<!&frac58;_\&#x215d;_geI
  sm_\C\\\@<!&frac78;_\&#x215e;_geI
  sm_\C\\\@<!&frown;_\&#x2322;_geI
  sm_\C\\\@<!&Fscr;_\&#x2131;_geI
  sm_\C\\\@<!&fscr;_\&#x1d4bb;_geI
  sm_\C\\\@<!&gacute;_\&#x1f5;_geI
  sm_\C\\\@<!&Gammad;_\&#x3dc;_geI
  sm_\C\\\@<!&gammad;_\&#x3dd;_geI
  sm_\C\\\@<!&gap;_\&#x2a86;_geI
  sm_\C\\\@<!&Gbreve;_\&#x11e;_geI
  sm_\C\\\@<!&gbreve;_\&#x11f;_geI
  sm_\C\\\@<!&Gcedil;_\&#x122;_geI
  sm_\C\\\@<!&Gcirc;_\&#x11c;_geI
  sm_\C\\\@<!&gcirc;_\&#x11d;_geI
  sm_\C\\\@<!&Gcy;_\&#x413;_geI
  sm_\C\\\@<!&gcy;_\&#x433;_geI
  sm_\C\\\@<!&Gdot;_\&#x120;_geI
  sm_\C\\\@<!&gdot;_\&#x121;_geI
  sm_\C\\\@<!&gE;_\&#x2267;_geI
  sm_\C\\\@<!&gEl;_\&#x2a8c;_geI
  sm_\C\\\@<!&gel;_\&#x22db;_geI
  sm_\C\\\@<!&geq;_\&#x2265;_geI
  sm_\C\\\@<!&geqq;_\&#x2267;_geI
  sm_\C\\\@<!&geqslant;_\&#x2a7e;_geI
  sm_\C\\\@<!&ges;_\&#x2a7e;_geI
  sm_\C\\\@<!&gescc;_\&#x2aa9;_geI
  sm_\C\\\@<!&gesdot;_\&#x2a80;_geI
  sm_\C\\\@<!&gesdoto;_\&#x2a82;_geI
  sm_\C\\\@<!&gesdotol;_\&#x2a84;_geI
  sm_\C\\\@<!&gesles;_\&#x2a94;_geI
  sm_\C\\\@<!&Gfr;_\&#x1d50a;_geI
  sm_\C\\\@<!&gfr;_\&#x1d524;_geI
  sm_\C\\\@<!&Gg;_\&#x22d9;_geI
  sm_\C\\\@<!&gg;_\&#x226b;_geI
  sm_\C\\\@<!&ggg;_\&#x22d9;_geI
  sm_\C\\\@<!&gimel;_\&#x2137;_geI
  sm_\C\\\@<!&GJcy;_\&#x403;_geI
  sm_\C\\\@<!&gjcy;_\&#x453;_geI
  sm_\C\\\@<!&gl;_\&#x2277;_geI
  sm_\C\\\@<!&gla;_\&#x2aa5;_geI
  sm_\C\\\@<!&glE;_\&#x2a92;_geI
  sm_\C\\\@<!&glj;_\&#x2aa4;_geI
  sm_\C\\\@<!&gnap;_\&#x2a8a;_geI
  sm_\C\\\@<!&gnapprox;_\&#x2a8a;_geI
  sm_\C\\\@<!&gnE;_\&#x2269;_geI
  sm_\C\\\@<!&gne;_\&#x2a88;_geI
  sm_\C\\\@<!&gneq;_\&#x2a88;_geI
  sm_\C\\\@<!&gneqq;_\&#x2269;_geI
  sm_\C\\\@<!&gnsim;_\&#x220000000;_geI
  sm_\C\\\@<!&Gopf;_\&#x1d53e;_geI
  sm_\C\\\@<!&gopf;_\&#x1d558;_geI
  if a:q=~'s'|sm_\C\\\@<!&grave;_\&#x60;_geI|endif
  sm_\C\\\@<!&GreaterEqual;_\&#x2265;_geI
  sm_\C\\\@<!&GreaterEqualLess;_\&#x22db;_geI
  sm_\C\\\@<!&GreaterFullEqual;_\&#x2267;_geI
  sm_\C\\\@<!&GreaterGreater;_\&#x2aa2;_geI
  sm_\C\\\@<!&GreaterLess;_\&#x2277;_geI
  sm_\C\\\@<!&GreaterSlantEqual;_\&#x2a7e;_geI
  sm_\C\\\@<!&GreaterTilde;_\&#x2273;_geI
  sm_\C\\\@<!&Gscr;_\&#x1d4a2;_geI
  sm_\C\\\@<!&gscr;_\&#x210a;_geI
  sm_\C\\\@<!&gsim;_\&#x2273;_geI
  sm_\C\\\@<!&gsime;_\&#x2a8e;_geI
  sm_\C\\\@<!&gsiml;_\&#x2a90;_geI
  if a:q=~'s'|sm_\C\\\@<!&GT;_\&#x3e;_geI|endif
  sm_\C\\\@<!&Gt;_\&#x226b;_geI
  sm_\C\\\@<!&gtcc;_\&#x2aa7;_geI
  sm_\C\\\@<!&gtcir;_\&#x2a7a;_geI
  sm_\C\\\@<!&gtdot;_\&#x22d7;_geI
  sm_\C\\\@<!&gtlPar;_\&#x2995;_geI
  sm_\C\\\@<!&gtquest;_\&#x2a7c;_geI
  sm_\C\\\@<!&gtrapprox;_\&#x2a86;_geI
  sm_\C\\\@<!&gtrarr;_\&#x2978;_geI
  sm_\C\\\@<!&gtrdot;_\&#x22d7;_geI
  sm_\C\\\@<!&gtreqless;_\&#x22db;_geI
  sm_\C\\\@<!&gtreqqless;_\&#x2a8c;_geI
  sm_\C\\\@<!&gtrless;_\&#x2277;_geI
  sm_\C\\\@<!&gtrsim;_\&#x2273;_geI
  sm_\C\\\@<!&Hacek;_\&#x2c7;_geI
  sm_\C\\\@<!&hairsp;_\&#x200a;_geI
  sm_\C\\\@<!&half;_\&#xbd;_geI
  sm_\C\\\@<!&hamilt;_\&#x210b;_geI
  sm_\C\\\@<!&HARDcy;_\&#x42a;_geI
  sm_\C\\\@<!&hardcy;_\&#x44a;_geI
  sm_\C\\\@<!&harrcir;_\&#x2948;_geI
  sm_\C\\\@<!&harrw;_\&#x21ad;_geI
  if a:q=~'s'|sm_\C\\\@<!&Hat;_\&#x5e;_geI|endif
  sm_\C\\\@<!&hbar;_\&#x210f;_geI
  sm_\C\\\@<!&Hcirc;_\&#x124;_geI
  sm_\C\\\@<!&hcirc;_\&#x125;_geI
  sm_\C\\\@<!&heartsuit;_\&#x2665;_geI
  sm_\C\\\@<!&hercon;_\&#x22b9;_geI
  sm_\C\\\@<!&Hfr;_\&#x210c;_geI
  sm_\C\\\@<!&hfr;_\&#x1d525;_geI
  sm_\C\\\@<!&HilbertSpace;_\&#x210b;_geI
  sm_\C\\\@<!&hksearow;_\&#x2925;_geI
  sm_\C\\\@<!&hkswarow;_\&#x2926;_geI
  sm_\C\\\@<!&hoarr;_\&#x21ff;_geI
  sm_\C\\\@<!&homtht;_\&#x223b;_geI
  sm_\C\\\@<!&hookleftarrow;_\&#x21a9;_geI
  sm_\C\\\@<!&hookrightarrow;_\&#x21aa;_geI
  sm_\C\\\@<!&Hopf;_\&#x210d;_geI
  sm_\C\\\@<!&hopf;_\&#x1d559;_geI
  sm_\C\\\@<!&horbar;_\&#x2015;_geI
  sm_\C\\\@<!&HorizontalLine;_\&#x2500;_geI
  sm_\C\\\@<!&Hscr;_\&#x210b;_geI
  sm_\C\\\@<!&hscr;_\&#x1d4bd;_geI
  sm_\C\\\@<!&hslash;_\&#x210f;_geI
  sm_\C\\\@<!&Hstrok;_\&#x126;_geI
  sm_\C\\\@<!&hstrok;_\&#x127;_geI
  sm_\C\\\@<!&HumpDownHump;_\&#x224e;_geI
  sm_\C\\\@<!&HumpEqual;_\&#x224f;_geI
  sm_\C\\\@<!&hybull;_\&#x2043;_geI
  sm_\C\\\@<!&hyphen;_\&#x2010;_geI
  sm_\C\\\@<!&ic;_\&#x2063;_geI
  sm_\C\\\@<!&Icy;_\&#x418;_geI
  sm_\C\\\@<!&icy;_\&#x438;_geI
  sm_\C\\\@<!&Idot;_\&#x130;_geI
  sm_\C\\\@<!&IEcy;_\&#x415;_geI
  sm_\C\\\@<!&iecy;_\&#x435;_geI
  sm_\C\\\@<!&iff;_\&#x21d4;_geI
  sm_\C\\\@<!&Ifr;_\&#x2111;_geI
  sm_\C\\\@<!&ifr;_\&#x1d526;_geI
  sm_\C\\\@<!&ii;_\&#x2148;_geI
  sm_\C\\\@<!&iiiint;_\&#x2a0c;_geI
  sm_\C\\\@<!&iiint;_\&#x222d;_geI
  sm_\C\\\@<!&iinfin;_\&#x29dc;_geI
  sm_\C\\\@<!&iiota;_\&#x2129;_geI
  sm_\C\\\@<!&IJlig;_\&#x132;_geI
  sm_\C\\\@<!&ijlig;_\&#x133;_geI
  sm_\C\\\@<!&Im;_\&#x2111;_geI
  sm_\C\\\@<!&Imacr;_\&#x12a;_geI
  sm_\C\\\@<!&imacr;_\&#x12b;_geI
  sm_\C\\\@<!&ImaginaryI;_\&#x2148;_geI
  sm_\C\\\@<!&imagline;_\&#x2110;_geI
  sm_\C\\\@<!&imagpart;_\&#x2111;_geI
  sm_\C\\\@<!&imath;_\&#x131;_geI
  sm_\C\\\@<!&imof;_\&#x22b7;_geI
  sm_\C\\\@<!&imped;_\&#x1b5;_geI
  sm_\C\\\@<!&Implies;_\&#x21d2;_geI
  sm_\C\\\@<!&in;_\&#x2208;_geI
  sm_\C\\\@<!&incare;_\&#x2105;_geI
  sm_\C\\\@<!&infintie;_\&#x29dd;_geI
  sm_\C\\\@<!&inodot;_\&#x131;_geI
  sm_\C\\\@<!&Int;_\&#x222c;_geI
  sm_\C\\\@<!&intcal;_\&#x22ba;_geI
  sm_\C\\\@<!&integers;_\&#x2124;_geI
  sm_\C\\\@<!&Integral;_\&#x222b;_geI
  sm_\C\\\@<!&intercal;_\&#x22ba;_geI
  sm_\C\\\@<!&Intersection;_\&#x22c2;_geI
  sm_\C\\\@<!&intlarhk;_\&#x2a17;_geI
  sm_\C\\\@<!&intprod;_\&#x2a3c;_geI
  sm_\C\\\@<!&InvisibleComma;_\&#x2063;_geI
  sm_\C\\\@<!&InvisibleTimes;_\&#x2062;_geI
  sm_\C\\\@<!&IOcy;_\&#x401;_geI
  sm_\C\\\@<!&iocy;_\&#x451;_geI
  sm_\C\\\@<!&Iogon;_\&#x12e;_geI
  sm_\C\\\@<!&iogon;_\&#x12f;_geI
  sm_\C\\\@<!&Iopf;_\&#x1d540;_geI
  sm_\C\\\@<!&iopf;_\&#x1d55a;_geI
  sm_\C\\\@<!&iprod;_\&#x2a3c;_geI
  sm_\C\\\@<!&Iscr;_\&#x2110;_geI
  sm_\C\\\@<!&iscr;_\&#x1d4be;_geI
  sm_\C\\\@<!&isindot;_\&#x22f5;_geI
  sm_\C\\\@<!&isinE;_\&#x22f9;_geI
  sm_\C\\\@<!&isins;_\&#x22f4;_geI
  sm_\C\\\@<!&isinsv;_\&#x22f3;_geI
  sm_\C\\\@<!&isinv;_\&#x2208;_geI
  sm_\C\\\@<!&it;_\&#x2062;_geI
  sm_\C\\\@<!&Itilde;_\&#x128;_geI
  sm_\C\\\@<!&itilde;_\&#x129;_geI
  sm_\C\\\@<!&Iukcy;_\&#x406;_geI
  sm_\C\\\@<!&iukcy;_\&#x456;_geI
  sm_\C\\\@<!&Jcirc;_\&#x134;_geI
  sm_\C\\\@<!&jcirc;_\&#x135;_geI
  sm_\C\\\@<!&Jcy;_\&#x419;_geI
  sm_\C\\\@<!&jcy;_\&#x439;_geI
  sm_\C\\\@<!&Jfr;_\&#x1d50d;_geI
  sm_\C\\\@<!&jfr;_\&#x1d527;_geI
  sm_\C\\\@<!&jmath;_\&#x237;_geI
  sm_\C\\\@<!&Jopf;_\&#x1d541;_geI
  sm_\C\\\@<!&jopf;_\&#x1d55b;_geI
  sm_\C\\\@<!&Jscr;_\&#x1d4a5;_geI
  sm_\C\\\@<!&jscr;_\&#x1d4bf;_geI
  sm_\C\\\@<!&Jsercy;_\&#x408;_geI
  sm_\C\\\@<!&jsercy;_\&#x458;_geI
  sm_\C\\\@<!&Jukcy;_\&#x404;_geI
  sm_\C\\\@<!&jukcy;_\&#x454;_geI
  sm_\C\\\@<!&kappav;_\&#x3f0;_geI
  sm_\C\\\@<!&Kcedil;_\&#x136;_geI
  sm_\C\\\@<!&kcedil;_\&#x137;_geI
  sm_\C\\\@<!&Kcy;_\&#x41a;_geI
  sm_\C\\\@<!&kcy;_\&#x43a;_geI
  sm_\C\\\@<!&Kfr;_\&#x1d50e;_geI
  sm_\C\\\@<!&kfr;_\&#x1d528;_geI
  sm_\C\\\@<!&kgreen;_\&#x138;_geI
  sm_\C\\\@<!&KHcy;_\&#x425;_geI
  sm_\C\\\@<!&khcy;_\&#x445;_geI
  sm_\C\\\@<!&KJcy;_\&#x40c;_geI
  sm_\C\\\@<!&kjcy;_\&#x45c;_geI
  sm_\C\\\@<!&Kopf;_\&#x1d542;_geI
  sm_\C\\\@<!&kopf;_\&#x1d55c;_geI
  sm_\C\\\@<!&Kscr;_\&#x1d4a6;_geI
  sm_\C\\\@<!&kscr;_\&#x1d4c0;_geI
  sm_\C\\\@<!&lAarr;_\&#x21da;_geI
  sm_\C\\\@<!&Lacute;_\&#x139;_geI
  sm_\C\\\@<!&lacute;_\&#x13a;_geI
  sm_\C\\\@<!&laemptyv;_\&#x29b4;_geI
  sm_\C\\\@<!&lagran;_\&#x2112;_geI
  sm_\C\\\@<!&Lang;_\&#x27ea;_geI
  sm_\C\\\@<!&langd;_\&#x2991;_geI
  sm_\C\\\@<!&langle;_\&#x2700000000;_geI
  sm_\C\\\@<!&lap;_\&#x2a85;_geI
  sm_\C\\\@<!&Laplacetrf;_\&#x2112;_geI
  sm_\C\\\@<!&Larr;_\&#x219e;_geI
  sm_\C\\\@<!&larrb;_\&#x210000;_geI
  sm_\C\\\@<!&larrbfs;_\&#x291f;_geI
  sm_\C\\\@<!&larrfs;_\&#x291d;_geI
  sm_\C\\\@<!&larrhk;_\&#x21a9;_geI
  sm_\C\\\@<!&larrlp;_\&#x21ab;_geI
  sm_\C\\\@<!&larrpl;_\&#x2939;_geI
  sm_\C\\\@<!&larrsim;_\&#x2973;_geI
  sm_\C\\\@<!&larrtl;_\&#x21a2;_geI
  sm_\C\\\@<!&lat;_\&#x2aab;_geI
  sm_\C\\\@<!&lAtail;_\&#x291b;_geI
  sm_\C\\\@<!&latail;_\&#x2919;_geI
  sm_\C\\\@<!&late;_\&#x2aad;_geI
  sm_\C\\\@<!&lBarr;_\&#x290e;_geI
  sm_\C\\\@<!&lbarr;_\&#x290c;_geI
  sm_\C\\\@<!&lbbrk;_\&#x2772;_geI
  if a:q=~'s'|sm_\C\\\@<!&lbrace;_\&#x7b;_geI|endif
  if a:q=~'s'|sm_\C\\\@<!&lbrack;_\&#x5b;_geI|endif
  sm_\C\\\@<!&lbrke;_\&#x298b;_geI
  sm_\C\\\@<!&lbrksld;_\&#x298f;_geI
  sm_\C\\\@<!&lbrkslu;_\&#x298d;_geI
  sm_\C\\\@<!&Lcaron;_\&#x13d;_geI
  sm_\C\\\@<!&lcaron;_\&#x13e;_geI
  sm_\C\\\@<!&Lcedil;_\&#x13b;_geI
  sm_\C\\\@<!&lcedil;_\&#x13c;_geI
  if a:q=~'s'|sm_\C\\\@<!&lcub;_\&#x7b;_geI|endif
  sm_\C\\\@<!&Lcy;_\&#x41b;_geI
  sm_\C\\\@<!&lcy;_\&#x43b;_geI
  sm_\C\\\@<!&ldca;_\&#x2936;_geI
  sm_\C\\\@<!&ldquor;_\&#x201e;_geI
  sm_\C\\\@<!&ldrdhar;_\&#x2967;_geI
  sm_\C\\\@<!&ldrushar;_\&#x294b;_geI
  sm_\C\\\@<!&ldsh;_\&#x21b2;_geI
  sm_\C\\\@<!&lE;_\&#x2266;_geI
  sm_\C\\\@<!&LeftAngleBracket;_\&#x2700000000;_geI
  sm_\C\\\@<!&LeftArrow;_\&#x2190;_geI
  sm_\C\\\@<!&Leftarrow;_\&#x21d0;_geI
  sm_\C\\\@<!&leftarrow;_\&#x2190;_geI
  sm_\C\\\@<!&LeftArrowBar;_\&#x210000;_geI
  sm_\C\\\@<!&LeftArrowRightArrow;_\&#x21c6;_geI
  sm_\C\\\@<!&leftarrowtail;_\&#x21a2;_geI
  sm_\C\\\@<!&LeftCeiling;_\&#x2308;_geI
  sm_\C\\\@<!&LeftDoubleBracket;_\&#x27000000;_geI
  sm_\C\\\@<!&LeftDownTeeVector;_\&#x2961;_geI
  sm_\C\\\@<!&LeftDownVector;_\&#x21c3;_geI
  sm_\C\\\@<!&LeftDownVectorBar;_\&#x2959;_geI
  sm_\C\\\@<!&LeftFloor;_\&#x230a;_geI
  sm_\C\\\@<!&leftharpoondown;_\&#x21bd;_geI
  sm_\C\\\@<!&leftharpoonup;_\&#x21bc;_geI
  sm_\C\\\@<!&leftleftarrows;_\&#x21c7;_geI
  sm_\C\\\@<!&LeftRightArrow;_\&#x2194;_geI
  sm_\C\\\@<!&Leftrightarrow;_\&#x21d4;_geI
  sm_\C\\\@<!&leftrightarrow;_\&#x2194;_geI
  sm_\C\\\@<!&leftrightarrows;_\&#x21c6;_geI
  sm_\C\\\@<!&leftrightharpoons;_\&#x21cb;_geI
  sm_\C\\\@<!&leftrightsquigarrow;_\&#x21ad;_geI
  sm_\C\\\@<!&LeftRightVector;_\&#x294e;_geI
  sm_\C\\\@<!&LeftTee;_\&#x22a3;_geI
  sm_\C\\\@<!&LeftTeeArrow;_\&#x21a4;_geI
  sm_\C\\\@<!&LeftTeeVector;_\&#x295a;_geI
  sm_\C\\\@<!&leftthreetimes;_\&#x22cb;_geI
  sm_\C\\\@<!&LeftTriangle;_\&#x22b2;_geI
  sm_\C\\\@<!&LeftTriangleBar;_\&#x29cf;_geI
  sm_\C\\\@<!&LeftTriangleEqual;_\&#x22b4;_geI
  sm_\C\\\@<!&LeftUpDownVector;_\&#x2951;_geI
  sm_\C\\\@<!&LeftUpTeeVector;_\&#x2960;_geI
  sm_\C\\\@<!&LeftUpVector;_\&#x21bf;_geI
  sm_\C\\\@<!&LeftUpVectorBar;_\&#x2958;_geI
  sm_\C\\\@<!&LeftVector;_\&#x21bc;_geI
  sm_\C\\\@<!&LeftVectorBar;_\&#x2952;_geI
  sm_\C\\\@<!&lEg;_\&#x2a8b;_geI
  sm_\C\\\@<!&leg;_\&#x22da;_geI
  sm_\C\\\@<!&leq;_\&#x2264;_geI
  sm_\C\\\@<!&leqq;_\&#x2266;_geI
  sm_\C\\\@<!&leqslant;_\&#x2a7d;_geI
  sm_\C\\\@<!&les;_\&#x2a7d;_geI
  sm_\C\\\@<!&lescc;_\&#x2aa8;_geI
  sm_\C\\\@<!&lesdot;_\&#x2a7f;_geI
  sm_\C\\\@<!&lesdoto;_\&#x2a81;_geI
  sm_\C\\\@<!&lesdotor;_\&#x2a83;_geI
  sm_\C\\\@<!&lesges;_\&#x2a93;_geI
  sm_\C\\\@<!&lessapprox;_\&#x2a85;_geI
  sm_\C\\\@<!&lessdot;_\&#x22d6;_geI
  sm_\C\\\@<!&lesseqgtr;_\&#x22da;_geI
  sm_\C\\\@<!&lesseqqgtr;_\&#x2a8b;_geI
  sm_\C\\\@<!&LessEqualGreater;_\&#x22da;_geI
  sm_\C\\\@<!&LessFullEqual;_\&#x2266;_geI
  sm_\C\\\@<!&LessGreater;_\&#x2276;_geI
  sm_\C\\\@<!&lessgtr;_\&#x2276;_geI
  sm_\C\\\@<!&LessLess;_\&#x2aa1;_geI
  sm_\C\\\@<!&lesssim;_\&#x2272;_geI
  sm_\C\\\@<!&LessSlantEqual;_\&#x2a7d;_geI
  sm_\C\\\@<!&LessTilde;_\&#x2272;_geI
  sm_\C\\\@<!&lfisht;_\&#x297c;_geI
  sm_\C\\\@<!&Lfr;_\&#x1d50f;_geI
  sm_\C\\\@<!&lfr;_\&#x1d529;_geI
  sm_\C\\\@<!&lg;_\&#x2276;_geI
  sm_\C\\\@<!&lgE;_\&#x2a91;_geI
  sm_\C\\\@<!&lHar;_\&#x2962;_geI
  sm_\C\\\@<!&lhard;_\&#x21bd;_geI
  sm_\C\\\@<!&lharu;_\&#x21bc;_geI
  sm_\C\\\@<!&lharul;_\&#x296a;_geI
  sm_\C\\\@<!&lhblk;_\&#x2584;_geI
  sm_\C\\\@<!&LJcy;_\&#x409;_geI
  sm_\C\\\@<!&ljcy;_\&#x459;_geI
  sm_\C\\\@<!&Ll;_\&#x22d8;_geI
  sm_\C\\\@<!&ll;_\&#x226a;_geI
  sm_\C\\\@<!&llarr;_\&#x21c7;_geI
  sm_\C\\\@<!&llcorner;_\&#x231e;_geI
  sm_\C\\\@<!&Lleftarrow;_\&#x21da;_geI
  sm_\C\\\@<!&llhard;_\&#x296b;_geI
  sm_\C\\\@<!&lltri;_\&#x25fa;_geI
  sm_\C\\\@<!&Lmidot;_\&#x13f;_geI
  sm_\C\\\@<!&lmidot;_\&#x140;_geI
  sm_\C\\\@<!&lmoust;_\&#x23b0;_geI
  sm_\C\\\@<!&lmoustache;_\&#x23b0;_geI
  sm_\C\\\@<!&lnap;_\&#x2a89;_geI
  sm_\C\\\@<!&lnapprox;_\&#x2a89;_geI
  sm_\C\\\@<!&lnE;_\&#x2268;_geI
  sm_\C\\\@<!&lne;_\&#x2a87;_geI
  sm_\C\\\@<!&lneq;_\&#x2a87;_geI
  sm_\C\\\@<!&lneqq;_\&#x2268;_geI
  sm_\C\\\@<!&lnsim;_\&#x22000000;_geI
  sm_\C\\\@<!&loang;_\&#x27ec;_geI
  sm_\C\\\@<!&loarr;_\&#x21fd;_geI
  sm_\C\\\@<!&lobrk;_\&#x27000000;_geI
  sm_\C\\\@<!&LongLeftArrow;_\&#x27f5;_geI
  sm_\C\\\@<!&Longleftarrow;_\&#x27f8;_geI
  sm_\C\\\@<!&longleftarrow;_\&#x27f5;_geI
  sm_\C\\\@<!&LongLeftRightArrow;_\&#x27f7;_geI
  sm_\C\\\@<!&Longleftrightarrow;_\&#x27fa;_geI
  sm_\C\\\@<!&longleftrightarrow;_\&#x27f7;_geI
  sm_\C\\\@<!&longmapsto;_\&#x27fc;_geI
  sm_\C\\\@<!&LongRightArrow;_\&#x27f6;_geI
  sm_\C\\\@<!&Longrightarrow;_\&#x27f9;_geI
  sm_\C\\\@<!&longrightarrow;_\&#x27f6;_geI
  sm_\C\\\@<!&looparrowleft;_\&#x21ab;_geI
  sm_\C\\\@<!&looparrowright;_\&#x21ac;_geI
  sm_\C\\\@<!&lopar;_\&#x2985;_geI
  sm_\C\\\@<!&Lopf;_\&#x1d543;_geI
  sm_\C\\\@<!&lopf;_\&#x1d55d;_geI
  sm_\C\\\@<!&loplus;_\&#x2a2d;_geI
  sm_\C\\\@<!&lotimes;_\&#x2a34;_geI
  if a:q=~'s'|sm_\C\\\@<!&lowbar;_\&#x5f;_geI|endif
  sm_\C\\\@<!&LowerLeftArrow;_\&#x2199;_geI
  sm_\C\\\@<!&LowerRightArrow;_\&#x2198;_geI
  sm_\C\\\@<!&lozenge;_\&#x25ca;_geI
  sm_\C\\\@<!&lozf;_\&#x29eb;_geI
  if a:q=~'s'|sm_\C\\\@<!&lpar;_\&#x28;_geI|endif
  sm_\C\\\@<!&lparlt;_\&#x2993;_geI
  sm_\C\\\@<!&lrarr;_\&#x21c6;_geI
  sm_\C\\\@<!&lrcorner;_\&#x231f;_geI
  sm_\C\\\@<!&lrhar;_\&#x21cb;_geI
  sm_\C\\\@<!&lrhard;_\&#x296d;_geI
  sm_\C\\\@<!&lrtri;_\&#x22bf;_geI
  sm_\C\\\@<!&Lscr;_\&#x2112;_geI
  sm_\C\\\@<!&lscr;_\&#x1d4c1;_geI
  sm_\C\\\@<!&Lsh;_\&#x21b0;_geI
  sm_\C\\\@<!&lsh;_\&#x21b0;_geI
  sm_\C\\\@<!&lsim;_\&#x2272;_geI
  sm_\C\\\@<!&lsime;_\&#x2a8d;_geI
  sm_\C\\\@<!&lsimg;_\&#x2a8f;_geI
  if a:q=~'s'|sm_\C\\\@<!&lsqb;_\&#x5b;_geI|endif
  sm_\C\\\@<!&lsquor;_\&#x201a;_geI
  sm_\C\\\@<!&Lstrok;_\&#x141;_geI
  sm_\C\\\@<!&lstrok;_\&#x142;_geI
  if a:q=~'s'|sm_\C\\\@<!&LT;_\&#x3c;_geI|endif
  sm_\C\\\@<!&Lt;_\&#x226a;_geI
  sm_\C\\\@<!&ltcc;_\&#x2aa6;_geI
  sm_\C\\\@<!&ltcir;_\&#x2a79;_geI
  sm_\C\\\@<!&ltdot;_\&#x22d6;_geI
  sm_\C\\\@<!&lthree;_\&#x22cb;_geI
  sm_\C\\\@<!&ltimes;_\&#x22c9;_geI
  sm_\C\\\@<!&ltlarr;_\&#x2976;_geI
  sm_\C\\\@<!&ltquest;_\&#x2a7b;_geI
  sm_\C\\\@<!&ltri;_\&#x25c3;_geI
  sm_\C\\\@<!&ltrie;_\&#x22b4;_geI
  sm_\C\\\@<!&ltrif;_\&#x25c2;_geI
  sm_\C\\\@<!&ltrPar;_\&#x2996;_geI
  sm_\C\\\@<!&lurdshar;_\&#x294a;_geI
  sm_\C\\\@<!&luruhar;_\&#x2966;_geI
  sm_\C\\\@<!&male;_\&#x2642;_geI
  sm_\C\\\@<!&malt;_\&#x2720;_geI
  sm_\C\\\@<!&maltese;_\&#x2720;_geI
  sm_\C\\\@<!&Map;_\&#x2905;_geI
  sm_\C\\\@<!&map;_\&#x21a6;_geI
  sm_\C\\\@<!&mapsto;_\&#x21a6;_geI
  sm_\C\\\@<!&mapstodown;_\&#x21a7;_geI
  sm_\C\\\@<!&mapstoleft;_\&#x21a4;_geI
  sm_\C\\\@<!&mapstoup;_\&#x21a5;_geI
  sm_\C\\\@<!&marker;_\&#x25ae;_geI
  sm_\C\\\@<!&mcomma;_\&#x2a29;_geI
  sm_\C\\\@<!&Mcy;_\&#x41c;_geI
  sm_\C\\\@<!&mcy;_\&#x43c;_geI
  sm_\C\\\@<!&mDDot;_\&#x223a;_geI
  sm_\C\\\@<!&measuredangle;_\&#x2221;_geI
  sm_\C\\\@<!&MediumSpace;_\&#x205f;_geI
  sm_\C\\\@<!&Mellintrf;_\&#x2133;_geI
  sm_\C\\\@<!&Mfr;_\&#x1d510;_geI
  sm_\C\\\@<!&mfr;_\&#x1d52a;_geI
  sm_\C\\\@<!&mho;_\&#x2127;_geI
  sm_\C\\\@<!&mid;_\&#x2223;_geI
  if a:q=~'s'|sm_\C\\\@<!&midast;_\&#x2a;_geI|endif
  sm_\C\\\@<!&midcir;_\&#x2af0;_geI
  sm_\C\\\@<!&minusb;_\&#x229f;_geI
  sm_\C\\\@<!&minusd;_\&#x2238;_geI
  sm_\C\\\@<!&minusdu;_\&#x2a2a;_geI
  sm_\C\\\@<!&MinusPlus;_\&#x2213;_geI
  sm_\C\\\@<!&mlcp;_\&#x2adb;_geI
  sm_\C\\\@<!&mldr;_\&#x2026;_geI
  sm_\C\\\@<!&mnplus;_\&#x2213;_geI
  sm_\C\\\@<!&models;_\&#x22a7;_geI
  sm_\C\\\@<!&Mopf;_\&#x1d544;_geI
  sm_\C\\\@<!&mopf;_\&#x1d55e;_geI
  sm_\C\\\@<!&mp;_\&#x2213;_geI
  sm_\C\\\@<!&Mscr;_\&#x2133;_geI
  sm_\C\\\@<!&mscr;_\&#x1d4c2;_geI
  sm_\C\\\@<!&mstpos;_\&#x223e;_geI
  sm_\C\\\@<!&multimap;_\&#x22b8;_geI
  sm_\C\\\@<!&mumap;_\&#x22b8;_geI
  sm_\C\\\@<!&Nacute;_\&#x143;_geI
  sm_\C\\\@<!&nacute;_\&#x144;_geI
  sm_\C\\\@<!&nap;_\&#x2249;_geI
  sm_\C\\\@<!&napos;_\&#x149;_geI
  sm_\C\\\@<!&napprox;_\&#x2249;_geI
  sm_\C\\\@<!&natur;_\&#x266e;_geI
  sm_\C\\\@<!&natural;_\&#x266e;_geI
  sm_\C\\\@<!&naturals;_\&#x2115;_geI
  sm_\C\\\@<!&ncap;_\&#x2a43;_geI
  sm_\C\\\@<!&Ncaron;_\&#x147;_geI
  sm_\C\\\@<!&ncaron;_\&#x148;_geI
  sm_\C\\\@<!&Ncedil;_\&#x145;_geI
  sm_\C\\\@<!&ncedil;_\&#x146;_geI
  sm_\C\\\@<!&ncong;_\&#x2247;_geI
  sm_\C\\\@<!&ncup;_\&#x2a42;_geI
  sm_\C\\\@<!&Ncy;_\&#x41d;_geI
  sm_\C\\\@<!&ncy;_\&#x43d;_geI
  sm_\C\\\@<!&nearhk;_\&#x2924;_geI
  sm_\C\\\@<!&neArr;_\&#x21d7;_geI
  sm_\C\\\@<!&nearr;_\&#x2197;_geI
  sm_\C\\\@<!&nearrow;_\&#x2197;_geI
  sm_\C\\\@<!&NegativeMediumSpace;_\&#x200b;_geI
  sm_\C\\\@<!&NegativeThickSpace;_\&#x200b;_geI
  sm_\C\\\@<!&NegativeThinSpace;_\&#x200b;_geI
  sm_\C\\\@<!&NegativeVeryThinSpace;_\&#x200b;_geI
  sm_\C\\\@<!&nequiv;_\&#x2262;_geI
  sm_\C\\\@<!&nesear;_\&#x2928;_geI
  sm_\C\\\@<!&NestedGreaterGreater;_\&#x226b;_geI
  sm_\C\\\@<!&NestedLessLess;_\&#x226a;_geI
  if a:q=~'c'|sm_\C\\\@<!&NewLine;_\&#xa;_geI|endif
  sm_\C\\\@<!&nexist;_\&#x2204;_geI
  sm_\C\\\@<!&nexists;_\&#x2204;_geI
  sm_\C\\\@<!&Nfr;_\&#x1d511;_geI
  sm_\C\\\@<!&nfr;_\&#x1d52b;_geI
  sm_\C\\\@<!&nge;_\&#x2271;_geI
  sm_\C\\\@<!&ngeq;_\&#x2271;_geI
  sm_\C\\\@<!&ngsim;_\&#x2275;_geI
  sm_\C\\\@<!&ngt;_\&#x226f;_geI
  sm_\C\\\@<!&ngtr;_\&#x226f;_geI
  sm_\C\\\@<!&nhArr;_\&#x21ce;_geI
  sm_\C\\\@<!&nharr;_\&#x21ae;_geI
  sm_\C\\\@<!&nhpar;_\&#x2af2;_geI
  sm_\C\\\@<!&nis;_\&#x22fc;_geI
  sm_\C\\\@<!&nisd;_\&#x22fa;_geI
  sm_\C\\\@<!&niv;_\&#x220b;_geI
  sm_\C\\\@<!&NJcy;_\&#x40a;_geI
  sm_\C\\\@<!&njcy;_\&#x45a;_geI
  sm_\C\\\@<!&nlArr;_\&#x21cd;_geI
  sm_\C\\\@<!&nlarr;_\&#x219a;_geI
  sm_\C\\\@<!&nldr;_\&#x2025;_geI
  sm_\C\\\@<!&nle;_\&#x2270;_geI
  sm_\C\\\@<!&nLeftarrow;_\&#x21cd;_geI
  sm_\C\\\@<!&nleftarrow;_\&#x219a;_geI
  sm_\C\\\@<!&nLeftrightarrow;_\&#x21ce;_geI
  sm_\C\\\@<!&nleftrightarrow;_\&#x21ae;_geI
  sm_\C\\\@<!&nleq;_\&#x2270;_geI
  sm_\C\\\@<!&nless;_\&#x226e;_geI
  sm_\C\\\@<!&nlsim;_\&#x2274;_geI
  sm_\C\\\@<!&nlt;_\&#x226e;_geI
  sm_\C\\\@<!&nltri;_\&#x22ea;_geI
  sm_\C\\\@<!&nltrie;_\&#x22ec;_geI
  sm_\C\\\@<!&nmid;_\&#x2224;_geI
  sm_\C\\\@<!&NoBreak;_\&#x2060;_geI
  sm_\C\\\@<!&NonBreakingSpace;_\&#xa0;_geI
  sm_\C\\\@<!&Nopf;_\&#x2115;_geI
  sm_\C\\\@<!&nopf;_\&#x1d55f;_geI
  sm_\C\\\@<!&Not;_\&#x2aec;_geI
  sm_\C\\\@<!&NotCongruent;_\&#x2262;_geI
  sm_\C\\\@<!&NotCupCap;_\&#x226d;_geI
  sm_\C\\\@<!&NotDoubleVerticalBar;_\&#x2226;_geI
  sm_\C\\\@<!&NotElement;_\&#x2209;_geI
  sm_\C\\\@<!&NotEqual;_\&#x2260;_geI
  sm_\C\\\@<!&NotExists;_\&#x2204;_geI
  sm_\C\\\@<!&NotGreater;_\&#x226f;_geI
  sm_\C\\\@<!&NotGreaterEqual;_\&#x2271;_geI
  sm_\C\\\@<!&NotGreaterLess;_\&#x2279;_geI
  sm_\C\\\@<!&NotGreaterTilde;_\&#x2275;_geI
  sm_\C\\\@<!&notinva;_\&#x2209;_geI
  sm_\C\\\@<!&notinvb;_\&#x22f7;_geI
  sm_\C\\\@<!&notinvc;_\&#x22f6;_geI
  sm_\C\\\@<!&NotLeftTriangle;_\&#x22ea;_geI
  sm_\C\\\@<!&NotLeftTriangleEqual;_\&#x22ec;_geI
  sm_\C\\\@<!&NotLess;_\&#x226e;_geI
  sm_\C\\\@<!&NotLessEqual;_\&#x2270;_geI
  sm_\C\\\@<!&NotLessGreater;_\&#x2278;_geI
  sm_\C\\\@<!&NotLessTilde;_\&#x2274;_geI
  sm_\C\\\@<!&notni;_\&#x220c;_geI
  sm_\C\\\@<!&notniva;_\&#x220c;_geI
  sm_\C\\\@<!&notnivb;_\&#x22fe;_geI
  sm_\C\\\@<!&notnivc;_\&#x22fd;_geI
  sm_\C\\\@<!&NotPrecedes;_\&#x2280;_geI
  sm_\C\\\@<!&NotPrecedesSlantEqual;_\&#x22;_geI
  sm_\C\\\@<!&NotReverseElement;_\&#x220c;_geI
  sm_\C\\\@<!&NotRightTriangle;_\&#x22eb;_geI
  sm_\C\\\@<!&NotRightTriangleEqual;_\&#x22ed;_geI
  sm_\C\\\@<!&NotSquareSubsetEqual;_\&#x2200;_geI
  sm_\C\\\@<!&NotSquareSupersetEqual;_\&#x22000;_geI
  sm_\C\\\@<!&NotSubsetEqual;_\&#x2288;_geI
  sm_\C\\\@<!&NotSucceeds;_\&#x2281;_geI
  sm_\C\\\@<!&NotSucceedsSlantEqual;_\&#x220;_geI
  sm_\C\\\@<!&NotSupersetEqual;_\&#x2289;_geI
  sm_\C\\\@<!&NotTilde;_\&#x2241;_geI
  sm_\C\\\@<!&NotTildeEqual;_\&#x2244;_geI
  sm_\C\\\@<!&NotTildeFullEqual;_\&#x2247;_geI
  sm_\C\\\@<!&NotTildeTilde;_\&#x2249;_geI
  sm_\C\\\@<!&NotVerticalBar;_\&#x2224;_geI
  sm_\C\\\@<!&npar;_\&#x2226;_geI
  sm_\C\\\@<!&nparallel;_\&#x2226;_geI
  sm_\C\\\@<!&npolint;_\&#x2a14;_geI
  sm_\C\\\@<!&npr;_\&#x2280;_geI
  sm_\C\\\@<!&nprcue;_\&#x22;_geI
  sm_\C\\\@<!&nprec;_\&#x2280;_geI
  sm_\C\\\@<!&nrArr;_\&#x21cf;_geI
  sm_\C\\\@<!&nrarr;_\&#x219b;_geI
  sm_\C\\\@<!&nRightarrow;_\&#x21cf;_geI
  sm_\C\\\@<!&nrightarrow;_\&#x219b;_geI
  sm_\C\\\@<!&nrtri;_\&#x22eb;_geI
  sm_\C\\\@<!&nrtrie;_\&#x22ed;_geI
  sm_\C\\\@<!&nsc;_\&#x2281;_geI
  sm_\C\\\@<!&nsccue;_\&#x220;_geI
  sm_\C\\\@<!&Nscr;_\&#x1d4a9;_geI
  sm_\C\\\@<!&nscr;_\&#x1d4c3;_geI
  sm_\C\\\@<!&nshortmid;_\&#x2224;_geI
  sm_\C\\\@<!&nshortparallel;_\&#x2226;_geI
  sm_\C\\\@<!&nsim;_\&#x2241;_geI
  sm_\C\\\@<!&nsime;_\&#x2244;_geI
  sm_\C\\\@<!&nsimeq;_\&#x2244;_geI
  sm_\C\\\@<!&nsmid;_\&#x2224;_geI
  sm_\C\\\@<!&nspar;_\&#x2226;_geI
  sm_\C\\\@<!&nsqsube;_\&#x2200;_geI
  sm_\C\\\@<!&nsqsupe;_\&#x22000;_geI
  sm_\C\\\@<!&nsube;_\&#x2288;_geI
  sm_\C\\\@<!&nsubseteq;_\&#x2288;_geI
  sm_\C\\\@<!&nsucc;_\&#x2281;_geI
  sm_\C\\\@<!&nsup;_\&#x2285;_geI
  sm_\C\\\@<!&nsupe;_\&#x2289;_geI
  sm_\C\\\@<!&nsupseteq;_\&#x2289;_geI
  sm_\C\\\@<!&ntgl;_\&#x2279;_geI
  sm_\C\\\@<!&ntlg;_\&#x2278;_geI
  sm_\C\\\@<!&ntriangleleft;_\&#x22ea;_geI
  sm_\C\\\@<!&ntrianglelefteq;_\&#x22ec;_geI
  sm_\C\\\@<!&ntriangleright;_\&#x22eb;_geI
  sm_\C\\\@<!&ntrianglerighteq;_\&#x22ed;_geI
  if a:q=~'s'|sm_\C\\\@<!&num;_\&#x23;_geI|endif
  sm_\C\\\@<!&numero;_\&#x2116;_geI
  sm_\C\\\@<!&numsp;_\&#x2007;_geI
  sm_\C\\\@<!&nVDash;_\&#x22af;_geI
  sm_\C\\\@<!&nVdash;_\&#x22ae;_geI
  sm_\C\\\@<!&nvDash;_\&#x22ad;_geI
  sm_\C\\\@<!&nvdash;_\&#x22ac;_geI
  sm_\C\\\@<!&nvHarr;_\&#x2904;_geI
  sm_\C\\\@<!&nvinfin;_\&#x29de;_geI
  sm_\C\\\@<!&nvlArr;_\&#x2902;_geI
  sm_\C\\\@<!&nvrArr;_\&#x2903;_geI
  sm_\C\\\@<!&nwarhk;_\&#x2923;_geI
  sm_\C\\\@<!&nwArr;_\&#x21d6;_geI
  sm_\C\\\@<!&nwarr;_\&#x2196;_geI
  sm_\C\\\@<!&nwarrow;_\&#x2196;_geI
  sm_\C\\\@<!&nwnear;_\&#x2927;_geI
  sm_\C\\\@<!&oast;_\&#x229b;_geI
  sm_\C\\\@<!&ocir;_\&#x229a;_geI
  sm_\C\\\@<!&Ocy;_\&#x41e;_geI
  sm_\C\\\@<!&ocy;_\&#x43e;_geI
  sm_\C\\\@<!&odash;_\&#x229d;_geI
  sm_\C\\\@<!&Odblac;_\&#x150;_geI
  sm_\C\\\@<!&odblac;_\&#x151;_geI
  sm_\C\\\@<!&odiv;_\&#x2a38;_geI
  sm_\C\\\@<!&odot;_\&#x2299;_geI
  sm_\C\\\@<!&odsold;_\&#x29bc;_geI
  sm_\C\\\@<!&ofcir;_\&#x29bf;_geI
  sm_\C\\\@<!&Ofr;_\&#x1d512;_geI
  sm_\C\\\@<!&ofr;_\&#x1d52c;_geI
  sm_\C\\\@<!&ogon;_\&#x2db;_geI
  sm_\C\\\@<!&ogt;_\&#x29c1;_geI
  sm_\C\\\@<!&ohbar;_\&#x29b5;_geI
  sm_\C\\\@<!&ohm;_\&#x3a9;_geI
  sm_\C\\\@<!&oint;_\&#x222e;_geI
  sm_\C\\\@<!&olarr;_\&#x21ba;_geI
  sm_\C\\\@<!&olcir;_\&#x29be;_geI
  sm_\C\\\@<!&olcross;_\&#x29bb;_geI
  sm_\C\\\@<!&olt;_\&#x29c0;_geI
  sm_\C\\\@<!&Omacr;_\&#x14c;_geI
  sm_\C\\\@<!&omacr;_\&#x14d;_geI
  sm_\C\\\@<!&omid;_\&#x29b6;_geI
  sm_\C\\\@<!&ominus;_\&#x2296;_geI
  sm_\C\\\@<!&Oopf;_\&#x1d546;_geI
  sm_\C\\\@<!&oopf;_\&#x1d560;_geI
  sm_\C\\\@<!&opar;_\&#x29b7;_geI
  sm_\C\\\@<!&OpenCurlyDoubleQuote;_\&#x201c;_geI
  sm_\C\\\@<!&OpenCurlyQuote;_\&#x2018;_geI
  sm_\C\\\@<!&operp;_\&#x29b9;_geI
  sm_\C\\\@<!&Or;_\&#x2a54;_geI
  sm_\C\\\@<!&orarr;_\&#x21bb;_geI
  sm_\C\\\@<!&ord;_\&#x2a5d;_geI
  sm_\C\\\@<!&order;_\&#x2134;_geI
  sm_\C\\\@<!&orderof;_\&#x2134;_geI
  sm_\C\\\@<!&origof;_\&#x22b6;_geI
  sm_\C\\\@<!&oror;_\&#x2a56;_geI
  sm_\C\\\@<!&orslope;_\&#x2a57;_geI
  sm_\C\\\@<!&orv;_\&#x2a5b;_geI
  sm_\C\\\@<!&oS;_\&#x24c8;_geI
  sm_\C\\\@<!&Oscr;_\&#x1d4aa;_geI
  sm_\C\\\@<!&oscr;_\&#x2134;_geI
  sm_\C\\\@<!&osol;_\&#x2298;_geI
  sm_\C\\\@<!&Otimes;_\&#x2a37;_geI
  sm_\C\\\@<!&otimesas;_\&#x2a36;_geI
  sm_\C\\\@<!&ovbar;_\&#x233d;_geI
  sm_\C\\\@<!&OverBar;_\&#x203e;_geI
  sm_\C\\\@<!&OverBrace;_\&#x23de;_geI
  sm_\C\\\@<!&OverBracket;_\&#x23b4;_geI
  sm_\C\\\@<!&OverParenthesis;_\&#x23dc;_geI
  sm_\C\\\@<!&par;_\&#x2225;_geI
  sm_\C\\\@<!&parallel;_\&#x2225;_geI
  sm_\C\\\@<!&parsim;_\&#x2af3;_geI
  sm_\C\\\@<!&parsl;_\&#x2afd;_geI
  sm_\C\\\@<!&PartialD;_\&#x2202;_geI
  sm_\C\\\@<!&Pcy;_\&#x41f;_geI
  sm_\C\\\@<!&pcy;_\&#x43f;_geI
  if a:q=~'s'|sm_\C\\\@<!&percnt;_\&#x25;_geI|endif
  if a:q=~'s'|sm_\C\\\@<!&period;_\&#x2e;_geI|endif
  sm_\C\\\@<!&pertenk;_\&#x2031;_geI
  sm_\C\\\@<!&Pfr;_\&#x1d513;_geI
  sm_\C\\\@<!&pfr;_\&#x1d52d;_geI
  sm_\C\\\@<!&phiv;_\&#x3d5;_geI
  sm_\C\\\@<!&phmmat;_\&#x2133;_geI
  sm_\C\\\@<!&phone;_\&#x260e;_geI
  sm_\C\\\@<!&pitchfork;_\&#x22d4;_geI
  sm_\C\\\@<!&planck;_\&#x210f;_geI
  sm_\C\\\@<!&planckh;_\&#x210e;_geI
  sm_\C\\\@<!&plankv;_\&#x210f;_geI
  if a:q=~'s'|sm_\C\\\@<!&plus;_\&#x2b;_geI|endif
  sm_\C\\\@<!&plusacir;_\&#x2a23;_geI
  sm_\C\\\@<!&plusb;_\&#x229e;_geI
  sm_\C\\\@<!&pluscir;_\&#x2a22;_geI
  sm_\C\\\@<!&plusdo;_\&#x2214;_geI
  sm_\C\\\@<!&plusdu;_\&#x2a25;_geI
  sm_\C\\\@<!&pluse;_\&#x2a72;_geI
  sm_\C\\\@<!&PlusMinus;_\&#xb1;_geI
  sm_\C\\\@<!&plussim;_\&#x2a26;_geI
  sm_\C\\\@<!&plustwo;_\&#x2a27;_geI
  sm_\C\\\@<!&pm;_\&#xb1;_geI
  sm_\C\\\@<!&Poincareplane;_\&#x210c;_geI
  sm_\C\\\@<!&pointint;_\&#x2a15;_geI
  sm_\C\\\@<!&Popf;_\&#x2119;_geI
  sm_\C\\\@<!&popf;_\&#x1d561;_geI
  sm_\C\\\@<!&Pr;_\&#x2abb;_geI
  sm_\C\\\@<!&pr;_\&#x227a;_geI
  sm_\C\\\@<!&prap;_\&#x2ab7;_geI
  sm_\C\\\@<!&prcue;_\&#x227c;_geI
  sm_\C\\\@<!&prE;_\&#x2ab3;_geI
  sm_\C\\\@<!&pre;_\&#x2aaf;_geI
  sm_\C\\\@<!&prec;_\&#x227a;_geI
  sm_\C\\\@<!&precapprox;_\&#x2ab7;_geI
  sm_\C\\\@<!&preccurlyeq;_\&#x227c;_geI
  sm_\C\\\@<!&Precedes;_\&#x227a;_geI
  sm_\C\\\@<!&PrecedesEqual;_\&#x2aaf;_geI
  sm_\C\\\@<!&PrecedesSlantEqual;_\&#x227c;_geI
  sm_\C\\\@<!&PrecedesTilde;_\&#x227e;_geI
  sm_\C\\\@<!&preceq;_\&#x2aaf;_geI
  sm_\C\\\@<!&precnapprox;_\&#x2ab9;_geI
  sm_\C\\\@<!&precneqq;_\&#x2ab5;_geI
  sm_\C\\\@<!&precnsim;_\&#x2200000000;_geI
  sm_\C\\\@<!&precsim;_\&#x227e;_geI
  sm_\C\\\@<!&primes;_\&#x2119;_geI
  sm_\C\\\@<!&prnap;_\&#x2ab9;_geI
  sm_\C\\\@<!&prnE;_\&#x2ab5;_geI
  sm_\C\\\@<!&prnsim;_\&#x2200000000;_geI
  sm_\C\\\@<!&Product;_\&#x220f;_geI
  sm_\C\\\@<!&profalar;_\&#x232e;_geI
  sm_\C\\\@<!&profline;_\&#x2312;_geI
  sm_\C\\\@<!&profsurf;_\&#x2313;_geI
  sm_\C\\\@<!&Proportion;_\&#x2237;_geI
  sm_\C\\\@<!&Proportional;_\&#x221d;_geI
  sm_\C\\\@<!&propto;_\&#x221d;_geI
  sm_\C\\\@<!&prsim;_\&#x227e;_geI
  sm_\C\\\@<!&prurel;_\&#x22b0;_geI
  sm_\C\\\@<!&Pscr;_\&#x1d4ab;_geI
  sm_\C\\\@<!&pscr;_\&#x1d4c5;_geI
  sm_\C\\\@<!&puncsp;_\&#x2008;_geI
  sm_\C\\\@<!&Qfr;_\&#x1d514;_geI
  sm_\C\\\@<!&qfr;_\&#x1d52e;_geI
  sm_\C\\\@<!&qint;_\&#x2a0c;_geI
  sm_\C\\\@<!&Qopf;_\&#x211a;_geI
  sm_\C\\\@<!&qopf;_\&#x1d562;_geI
  sm_\C\\\@<!&qprime;_\&#x2057;_geI
  sm_\C\\\@<!&Qscr;_\&#x1d4ac;_geI
  sm_\C\\\@<!&qscr;_\&#x1d4c6;_geI
  sm_\C\\\@<!&quaternions;_\&#x210d;_geI
  sm_\C\\\@<!&quatint;_\&#x2a16;_geI
  if a:q=~'s'|sm_\C\\\@<!&quest;_\&#x3f;_geI|endif
  sm_\C\\\@<!&questeq;_\&#x225f;_geI
  if a:q=~'s'|sm_\C\\\@<!&QUOT;_\&#x22;_geI|endif
  sm_\C\\\@<!&rAarr;_\&#x21db;_geI
  sm_\C\\\@<!&Racute;_\&#x154;_geI
  sm_\C\\\@<!&racute;_\&#x155;_geI
  sm_\C\\\@<!&raemptyv;_\&#x29b3;_geI
  sm_\C\\\@<!&Rang;_\&#x27eb;_geI
  sm_\C\\\@<!&rangd;_\&#x2992;_geI
  sm_\C\\\@<!&range;_\&#x29a5;_geI
  sm_\C\\\@<!&rangle;_\&#x27000000000;_geI
  sm_\C\\\@<!&Rarr;_\&#x21a0;_geI
  sm_\C\\\@<!&rarrap;_\&#x2975;_geI
  sm_\C\\\@<!&rarrb;_\&#x2100000;_geI
  sm_\C\\\@<!&rarrbfs;_\&#x2920;_geI
  sm_\C\\\@<!&rarrc;_\&#x2933;_geI
  sm_\C\\\@<!&rarrfs;_\&#x291e;_geI
  sm_\C\\\@<!&rarrhk;_\&#x21aa;_geI
  sm_\C\\\@<!&rarrlp;_\&#x21ac;_geI
  sm_\C\\\@<!&rarrpl;_\&#x2945;_geI
  sm_\C\\\@<!&rarrsim;_\&#x2974;_geI
  sm_\C\\\@<!&Rarrtl;_\&#x2916;_geI
  sm_\C\\\@<!&rarrtl;_\&#x21a3;_geI
  sm_\C\\\@<!&rarrw;_\&#x219d;_geI
  sm_\C\\\@<!&rAtail;_\&#x291c;_geI
  sm_\C\\\@<!&ratail;_\&#x291a;_geI
  sm_\C\\\@<!&ratio;_\&#x2236;_geI
  sm_\C\\\@<!&rationals;_\&#x211a;_geI
  sm_\C\\\@<!&RBarr;_\&#x2910;_geI
  sm_\C\\\@<!&rBarr;_\&#x290f;_geI
  sm_\C\\\@<!&rbarr;_\&#x290d;_geI
  sm_\C\\\@<!&rbbrk;_\&#x2773;_geI
  if a:q=~'s'|sm_\C\\\@<!&rbrace;_\&#x7d;_geI|endif
  if a:q=~'s'|sm_\C\\\@<!&rbrack;_\&#x5d;_geI|endif
  sm_\C\\\@<!&rbrke;_\&#x298c;_geI
  sm_\C\\\@<!&rbrksld;_\&#x298e;_geI
  sm_\C\\\@<!&rbrkslu;_\&#x2990;_geI
  sm_\C\\\@<!&Rcaron;_\&#x158;_geI
  sm_\C\\\@<!&rcaron;_\&#x159;_geI
  sm_\C\\\@<!&Rcedil;_\&#x156;_geI
  sm_\C\\\@<!&rcedil;_\&#x157;_geI
  if a:q=~'s'|sm_\C\\\@<!&rcub;_\&#x7d;_geI|endif
  sm_\C\\\@<!&Rcy;_\&#x420;_geI
  sm_\C\\\@<!&rcy;_\&#x440;_geI
  sm_\C\\\@<!&rdca;_\&#x2937;_geI
  sm_\C\\\@<!&rdldhar;_\&#x2969;_geI
  sm_\C\\\@<!&rdquor;_\&#x201d;_geI
  sm_\C\\\@<!&rdsh;_\&#x21b3;_geI
  sm_\C\\\@<!&Re;_\&#x211c;_geI
  sm_\C\\\@<!&realine;_\&#x211b;_geI
  sm_\C\\\@<!&realpart;_\&#x211c;_geI
  sm_\C\\\@<!&reals;_\&#x211d;_geI
  sm_\C\\\@<!&rect;_\&#x25ad;_geI
  sm_\C\\\@<!&REG;_\&#xae;_geI
  sm_\C\\\@<!&ReverseElement;_\&#x220b;_geI
  sm_\C\\\@<!&ReverseEquilibrium;_\&#x21cb;_geI
  sm_\C\\\@<!&ReverseUpEquilibrium;_\&#x296f;_geI
  sm_\C\\\@<!&rfisht;_\&#x297d;_geI
  sm_\C\\\@<!&Rfr;_\&#x211c;_geI
  sm_\C\\\@<!&rfr;_\&#x1d52f;_geI
  sm_\C\\\@<!&rHar;_\&#x2964;_geI
  sm_\C\\\@<!&rhard;_\&#x21c1;_geI
  sm_\C\\\@<!&rharu;_\&#x21c0;_geI
  sm_\C\\\@<!&rharul;_\&#x296c;_geI
  sm_\C\\\@<!&rhov;_\&#x3f1;_geI
  sm_\C\\\@<!&RightAngleBracket;_\&#x27000000000;_geI
  sm_\C\\\@<!&RightArrow;_\&#x2192;_geI
  sm_\C\\\@<!&Rightarrow;_\&#x21d2;_geI
  sm_\C\\\@<!&rightarrow;_\&#x2192;_geI
  sm_\C\\\@<!&RightArrowBar;_\&#x2100000;_geI
  sm_\C\\\@<!&RightArrowLeftArrow;_\&#x21c4;_geI
  sm_\C\\\@<!&rightarrowtail;_\&#x21a3;_geI
  sm_\C\\\@<!&RightCeiling;_\&#x2309;_geI
  sm_\C\\\@<!&RightDoubleBracket;_\&#x270000000;_geI
  sm_\C\\\@<!&RightDownTeeVector;_\&#x295d;_geI
  sm_\C\\\@<!&RightDownVector;_\&#x21c2;_geI
  sm_\C\\\@<!&RightDownVectorBar;_\&#x2955;_geI
  sm_\C\\\@<!&RightFloor;_\&#x230b;_geI
  sm_\C\\\@<!&rightharpoondown;_\&#x21c1;_geI
  sm_\C\\\@<!&rightharpoonup;_\&#x21c0;_geI
  sm_\C\\\@<!&rightleftarrows;_\&#x21c4;_geI
  sm_\C\\\@<!&rightleftharpoons;_\&#x21cc;_geI
  sm_\C\\\@<!&rightrightarrows;_\&#x21c9;_geI
  sm_\C\\\@<!&rightsquigarrow;_\&#x219d;_geI
  sm_\C\\\@<!&RightTee;_\&#x22a2;_geI
  sm_\C\\\@<!&RightTeeArrow;_\&#x21a6;_geI
  sm_\C\\\@<!&RightTeeVector;_\&#x295b;_geI
  sm_\C\\\@<!&rightthreetimes;_\&#x22cc;_geI
  sm_\C\\\@<!&RightTriangle;_\&#x22b3;_geI
  sm_\C\\\@<!&RightTriangleBar;_\&#x29d0;_geI
  sm_\C\\\@<!&RightTriangleEqual;_\&#x22b5;_geI
  sm_\C\\\@<!&RightUpDownVector;_\&#x294f;_geI
  sm_\C\\\@<!&RightUpTeeVector;_\&#x295c;_geI
  sm_\C\\\@<!&RightUpVector;_\&#x21be;_geI
  sm_\C\\\@<!&RightUpVectorBar;_\&#x2954;_geI
  sm_\C\\\@<!&RightVector;_\&#x21c0;_geI
  sm_\C\\\@<!&RightVectorBar;_\&#x2953;_geI
  sm_\C\\\@<!&ring;_\&#x2da;_geI
  sm_\C\\\@<!&risingdotseq;_\&#x2253;_geI
  sm_\C\\\@<!&rlarr;_\&#x21c4;_geI
  sm_\C\\\@<!&rlhar;_\&#x21cc;_geI
  sm_\C\\\@<!&rmoust;_\&#x23b1;_geI
  sm_\C\\\@<!&rmoustache;_\&#x23b1;_geI
  sm_\C\\\@<!&rnmid;_\&#x2aee;_geI
  sm_\C\\\@<!&roang;_\&#x27ed;_geI
  sm_\C\\\@<!&roarr;_\&#x21fe;_geI
  sm_\C\\\@<!&robrk;_\&#x270000000;_geI
  sm_\C\\\@<!&ropar;_\&#x2986;_geI
  sm_\C\\\@<!&Ropf;_\&#x211d;_geI
  sm_\C\\\@<!&ropf;_\&#x1d563;_geI
  sm_\C\\\@<!&roplus;_\&#x2a2e;_geI
  sm_\C\\\@<!&rotimes;_\&#x2a35;_geI
  sm_\C\\\@<!&RoundImplies;_\&#x2970;_geI
  if a:q=~'s'|sm_\C\\\@<!&rpar;_\&#x29;_geI|endif
  sm_\C\\\@<!&rpargt;_\&#x2994;_geI
  sm_\C\\\@<!&rppolint;_\&#x2a12;_geI
  sm_\C\\\@<!&rrarr;_\&#x21c9;_geI
  sm_\C\\\@<!&Rrightarrow;_\&#x21db;_geI
  sm_\C\\\@<!&Rscr;_\&#x211b;_geI
  sm_\C\\\@<!&rscr;_\&#x1d4c7;_geI
  sm_\C\\\@<!&Rsh;_\&#x21b1;_geI
  sm_\C\\\@<!&rsh;_\&#x21b1;_geI
  if a:q=~'s'|sm_\C\\\@<!&rsqb;_\&#x5d;_geI|endif
  sm_\C\\\@<!&rsquor;_\&#x2019;_geI
  sm_\C\\\@<!&rthree;_\&#x22cc;_geI
  sm_\C\\\@<!&rtimes;_\&#x22ca;_geI
  sm_\C\\\@<!&rtri;_\&#x25b9;_geI
  sm_\C\\\@<!&rtrie;_\&#x22b5;_geI
  sm_\C\\\@<!&rtrif;_\&#x25b8;_geI
  sm_\C\\\@<!&rtriltri;_\&#x29ce;_geI
  sm_\C\\\@<!&RuleDelayed;_\&#x29f4;_geI
  sm_\C\\\@<!&ruluhar;_\&#x2968;_geI
  sm_\C\\\@<!&rx;_\&#x211e;_geI
  sm_\C\\\@<!&Sacute;_\&#x15a;_geI
  sm_\C\\\@<!&sacute;_\&#x15b;_geI
  sm_\C\\\@<!&Sc;_\&#x2abc;_geI
  sm_\C\\\@<!&sc;_\&#x227b;_geI
  sm_\C\\\@<!&scap;_\&#x2ab8;_geI
  sm_\C\\\@<!&sccue;_\&#x227d;_geI
  sm_\C\\\@<!&scE;_\&#x2ab4;_geI
  sm_\C\\\@<!&sce;_\&#x2ab0;_geI
  sm_\C\\\@<!&Scedil;_\&#x15e;_geI
  sm_\C\\\@<!&scedil;_\&#x15f;_geI
  sm_\C\\\@<!&Scirc;_\&#x15c;_geI
  sm_\C\\\@<!&scirc;_\&#x15d;_geI
  sm_\C\\\@<!&scnap;_\&#x2aba;_geI
  sm_\C\\\@<!&scnE;_\&#x2ab6;_geI
  sm_\C\\\@<!&scnsim;_\&#x22000000000;_geI
  sm_\C\\\@<!&scpolint;_\&#x2a13;_geI
  sm_\C\\\@<!&scsim;_\&#x227f;_geI
  sm_\C\\\@<!&Scy;_\&#x421;_geI
  sm_\C\\\@<!&scy;_\&#x441;_geI
  sm_\C\\\@<!&sdotb;_\&#x22a1;_geI
  sm_\C\\\@<!&sdote;_\&#x2a66;_geI
  sm_\C\\\@<!&searhk;_\&#x2925;_geI
  sm_\C\\\@<!&seArr;_\&#x21d8;_geI
  sm_\C\\\@<!&searr;_\&#x2198;_geI
  sm_\C\\\@<!&searrow;_\&#x2198;_geI
  if a:q=~'s'|sm_\C\\\@<!&semi;_\&#x3b;_geI|endif
  sm_\C\\\@<!&seswar;_\&#x2929;_geI
  sm_\C\\\@<!&setminus;_\&#x2216;_geI
  sm_\C\\\@<!&setmn;_\&#x2216;_geI
  sm_\C\\\@<!&sext;_\&#x2736;_geI
  sm_\C\\\@<!&Sfr;_\&#x1d516;_geI
  sm_\C\\\@<!&sfr;_\&#x1d530;_geI
  sm_\C\\\@<!&sfrown;_\&#x2322;_geI
  sm_\C\\\@<!&sharp;_\&#x266f;_geI
  sm_\C\\\@<!&SHCHcy;_\&#x429;_geI
  sm_\C\\\@<!&shchcy;_\&#x449;_geI
  sm_\C\\\@<!&SHcy;_\&#x428;_geI
  sm_\C\\\@<!&shcy;_\&#x448;_geI
  sm_\C\\\@<!&ShortDownArrow;_\&#x2193;_geI
  sm_\C\\\@<!&ShortLeftArrow;_\&#x2190;_geI
  sm_\C\\\@<!&shortmid;_\&#x2223;_geI
  sm_\C\\\@<!&shortparallel;_\&#x2225;_geI
  sm_\C\\\@<!&ShortRightArrow;_\&#x2192;_geI
  sm_\C\\\@<!&ShortUpArrow;_\&#x2191;_geI
  sm_\C\\\@<!&sigmav;_\&#x3c2;_geI
  sm_\C\\\@<!&simdot;_\&#x2a6a;_geI
  sm_\C\\\@<!&sime;_\&#x2243;_geI
  sm_\C\\\@<!&simeq;_\&#x2243;_geI
  sm_\C\\\@<!&simg;_\&#x2a9e;_geI
  sm_\C\\\@<!&simgE;_\&#x2aa0;_geI
  sm_\C\\\@<!&siml;_\&#x2a9d;_geI
  sm_\C\\\@<!&simlE;_\&#x2a9f;_geI
  sm_\C\\\@<!&simne;_\&#x2246;_geI
  sm_\C\\\@<!&simplus;_\&#x2a24;_geI
  sm_\C\\\@<!&simrarr;_\&#x2972;_geI
  sm_\C\\\@<!&slarr;_\&#x2190;_geI
  sm_\C\\\@<!&SmallCircle;_\&#x2218;_geI
  sm_\C\\\@<!&smallsetminus;_\&#x2216;_geI
  sm_\C\\\@<!&smashp;_\&#x2a33;_geI
  sm_\C\\\@<!&smeparsl;_\&#x290000;_geI
  sm_\C\\\@<!&smid;_\&#x2223;_geI
  sm_\C\\\@<!&smile;_\&#x2323;_geI
  sm_\C\\\@<!&smt;_\&#x2aaa;_geI
  sm_\C\\\@<!&smte;_\&#x2aac;_geI
  sm_\C\\\@<!&SOFTcy;_\&#x42c;_geI
  sm_\C\\\@<!&softcy;_\&#x44c;_geI
  if a:q=~'s'|sm_\C\\\@<!&sol;_\&#x2f;_geI|endif
  sm_\C\\\@<!&solb;_\&#x29c4;_geI
  sm_\C\\\@<!&solbar;_\&#x233f;_geI
  sm_\C\\\@<!&Sopf;_\&#x1d54a;_geI
  sm_\C\\\@<!&sopf;_\&#x1d564;_geI
  sm_\C\\\@<!&spadesuit;_\&#x2660;_geI
  sm_\C\\\@<!&spar;_\&#x2225;_geI
  sm_\C\\\@<!&sqcap;_\&#x2293;_geI
  sm_\C\\\@<!&sqcup;_\&#x2294;_geI
  sm_\C\\\@<!&Sqrt;_\&#x221a;_geI
  sm_\C\\\@<!&sqsub;_\&#x228f;_geI
  sm_\C\\\@<!&sqsube;_\&#x2291;_geI
  sm_\C\\\@<!&sqsubset;_\&#x228f;_geI
  sm_\C\\\@<!&sqsubseteq;_\&#x2291;_geI
  sm_\C\\\@<!&sqsup;_\&#x2290;_geI
  sm_\C\\\@<!&sqsupe;_\&#x2292;_geI
  sm_\C\\\@<!&sqsupset;_\&#x2290;_geI
  sm_\C\\\@<!&sqsupseteq;_\&#x2292;_geI
  sm_\C\\\@<!&squ;_\&#x25a1;_geI
  sm_\C\\\@<!&Square;_\&#x25a1;_geI
  sm_\C\\\@<!&square;_\&#x25a1;_geI
  sm_\C\\\@<!&SquareIntersection;_\&#x2293;_geI
  sm_\C\\\@<!&SquareSubset;_\&#x228f;_geI
  sm_\C\\\@<!&SquareSubsetEqual;_\&#x2291;_geI
  sm_\C\\\@<!&SquareSuperset;_\&#x2290;_geI
  sm_\C\\\@<!&SquareSupersetEqual;_\&#x2292;_geI
  sm_\C\\\@<!&SquareUnion;_\&#x2294;_geI
  sm_\C\\\@<!&squarf;_\&#x25aa;_geI
  sm_\C\\\@<!&squf;_\&#x25aa;_geI
  sm_\C\\\@<!&srarr;_\&#x2192;_geI
  sm_\C\\\@<!&Sscr;_\&#x1d4ae;_geI
  sm_\C\\\@<!&sscr;_\&#x1d4c8;_geI
  sm_\C\\\@<!&ssetmn;_\&#x2216;_geI
  sm_\C\\\@<!&ssmile;_\&#x2323;_geI
  sm_\C\\\@<!&sstarf;_\&#x22c6;_geI
  sm_\C\\\@<!&Star;_\&#x22c6;_geI
  sm_\C\\\@<!&star;_\&#x2606;_geI
  sm_\C\\\@<!&starf;_\&#x2605;_geI
  sm_\C\\\@<!&straightepsilon;_\&#x3f5;_geI
  sm_\C\\\@<!&straightphi;_\&#x3d5;_geI
  sm_\C\\\@<!&strns;_\&#xaf;_geI
  sm_\C\\\@<!&Sub;_\&#x22d0;_geI
  sm_\C\\\@<!&subdot;_\&#x2abd;_geI
  sm_\C\\\@<!&subE;_\&#x2ac5;_geI
  sm_\C\\\@<!&subedot;_\&#x2ac3;_geI
  sm_\C\\\@<!&submult;_\&#x2ac1;_geI
  sm_\C\\\@<!&subnE;_\&#x2acb;_geI
  sm_\C\\\@<!&subne;_\&#x228a;_geI
  sm_\C\\\@<!&subplus;_\&#x2abf;_geI
  sm_\C\\\@<!&subrarr;_\&#x2979;_geI
  sm_\C\\\@<!&Subset;_\&#x22d0;_geI
  sm_\C\\\@<!&subset;_\&#x2282;_geI
  sm_\C\\\@<!&subseteq;_\&#x2286;_geI
  sm_\C\\\@<!&subseteqq;_\&#x2ac5;_geI
  sm_\C\\\@<!&SubsetEqual;_\&#x2286;_geI
  sm_\C\\\@<!&subsetneq;_\&#x228a;_geI
  sm_\C\\\@<!&subsetneqq;_\&#x2acb;_geI
  sm_\C\\\@<!&subsim;_\&#x2ac7;_geI
  sm_\C\\\@<!&subsub;_\&#x2ad5;_geI
  sm_\C\\\@<!&subsup;_\&#x2ad3;_geI
  sm_\C\\\@<!&succ;_\&#x227b;_geI
  sm_\C\\\@<!&succapprox;_\&#x2ab8;_geI
  sm_\C\\\@<!&succcurlyeq;_\&#x227d;_geI
  sm_\C\\\@<!&Succeeds;_\&#x227b;_geI
  sm_\C\\\@<!&SucceedsEqual;_\&#x2ab0;_geI
  sm_\C\\\@<!&SucceedsSlantEqual;_\&#x227d;_geI
  sm_\C\\\@<!&SucceedsTilde;_\&#x227f;_geI
  sm_\C\\\@<!&succeq;_\&#x2ab0;_geI
  sm_\C\\\@<!&succnapprox;_\&#x2aba;_geI
  sm_\C\\\@<!&succneqq;_\&#x2ab6;_geI
  sm_\C\\\@<!&succnsim;_\&#x22000000000;_geI
  sm_\C\\\@<!&succsim;_\&#x227f;_geI
  sm_\C\\\@<!&SuchThat;_\&#x220b;_geI
  sm_\C\\\@<!&Sum;_\&#x2211;_geI
  sm_\C\\\@<!&sung;_\&#x266a;_geI
  sm_\C\\\@<!&Sup;_\&#x22d1;_geI
  sm_\C\\\@<!&supdot;_\&#x2abe;_geI
  sm_\C\\\@<!&supdsub;_\&#x2ad8;_geI
  sm_\C\\\@<!&supE;_\&#x2ac6;_geI
  sm_\C\\\@<!&supedot;_\&#x2ac4;_geI
  sm_\C\\\@<!&Superset;_\&#x2283;_geI
  sm_\C\\\@<!&SupersetEqual;_\&#x2287;_geI
  sm_\C\\\@<!&suphsol;_\&#x27c9;_geI
  sm_\C\\\@<!&suphsub;_\&#x2ad7;_geI
  sm_\C\\\@<!&suplarr;_\&#x297b;_geI
  sm_\C\\\@<!&supmult;_\&#x2ac2;_geI
  sm_\C\\\@<!&supnE;_\&#x2acc;_geI
  sm_\C\\\@<!&supne;_\&#x228b;_geI
  sm_\C\\\@<!&supplus;_\&#x2ac0;_geI
  sm_\C\\\@<!&Supset;_\&#x22d1;_geI
  sm_\C\\\@<!&supset;_\&#x2283;_geI
  sm_\C\\\@<!&supseteq;_\&#x2287;_geI
  sm_\C\\\@<!&supseteqq;_\&#x2ac6;_geI
  sm_\C\\\@<!&supsetneq;_\&#x228b;_geI
  sm_\C\\\@<!&supsetneqq;_\&#x2acc;_geI
  sm_\C\\\@<!&supsim;_\&#x2ac8;_geI
  sm_\C\\\@<!&supsub;_\&#x2ad4;_geI
  sm_\C\\\@<!&supsup;_\&#x2ad6;_geI
  sm_\C\\\@<!&swarhk;_\&#x2926;_geI
  sm_\C\\\@<!&swArr;_\&#x21d9;_geI
  sm_\C\\\@<!&swarr;_\&#x2199;_geI
  sm_\C\\\@<!&swarrow;_\&#x2199;_geI
  sm_\C\\\@<!&swnwar;_\&#x292a;_geI
  if a:q=~'c'|sm_\C\\\@<!&Tab;_\&#x9;_geI|endif
  sm_\C\\\@<!&target;_\&#x2316;_geI
  sm_\C\\\@<!&tbrk;_\&#x23b4;_geI
  sm_\C\\\@<!&Tcaron;_\&#x164;_geI
  sm_\C\\\@<!&tcaron;_\&#x165;_geI
  sm_\C\\\@<!&Tcedil;_\&#x162;_geI
  sm_\C\\\@<!&tcedil;_\&#x163;_geI
  sm_\C\\\@<!&Tcy;_\&#x422;_geI
  sm_\C\\\@<!&tcy;_\&#x442;_geI
  sm_\C\\\@<!&tdot;_\&#x20db;_geI
  sm_\C\\\@<!&telrec;_\&#x2315;_geI
  sm_\C\\\@<!&Tfr;_\&#x1d517;_geI
  sm_\C\\\@<!&tfr;_\&#x1d531;_geI
  sm_\C\\\@<!&Therefore;_\&#x2234;_geI
  sm_\C\\\@<!&therefore;_\&#x2234;_geI
  sm_\C\\\@<!&thetav;_\&#x3d1;_geI
  sm_\C\\\@<!&thickapprox;_\&#x2248;_geI
  sm_\C\\\@<!&thicksim;_\&#x223c;_geI
  sm_\C\\\@<!&ThinSpace;_\&#x2009;_geI
  sm_\C\\\@<!&thkap;_\&#x2248;_geI
  sm_\C\\\@<!&thksim;_\&#x223c;_geI
  sm_\C\\\@<!&Tilde;_\&#x223c;_geI
  sm_\C\\\@<!&TildeEqual;_\&#x2243;_geI
  sm_\C\\\@<!&TildeFullEqual;_\&#x2245;_geI
  sm_\C\\\@<!&TildeTilde;_\&#x2248;_geI
  sm_\C\\\@<!&timesb;_\&#x22a0;_geI
  sm_\C\\\@<!&timesbar;_\&#x2a31;_geI
  sm_\C\\\@<!&timesd;_\&#x2a30;_geI
  sm_\C\\\@<!&tint;_\&#x222d;_geI
  sm_\C\\\@<!&toea;_\&#x2928;_geI
  sm_\C\\\@<!&top;_\&#x22a4;_geI
  sm_\C\\\@<!&topbot;_\&#x2336;_geI
  sm_\C\\\@<!&topcir;_\&#x2af1;_geI
  sm_\C\\\@<!&Topf;_\&#x1d54b;_geI
  sm_\C\\\@<!&topf;_\&#x1d565;_geI
  sm_\C\\\@<!&topfork;_\&#x2ada;_geI
  sm_\C\\\@<!&tosa;_\&#x2929;_geI
  sm_\C\\\@<!&tprime;_\&#x2034;_geI
  sm_\C\\\@<!&TRADE;_\&#x2122;_geI
  sm_\C\\\@<!&triangle;_\&#x25b5;_geI
  sm_\C\\\@<!&triangledown;_\&#x25bf;_geI
  sm_\C\\\@<!&triangleleft;_\&#x25c3;_geI
  sm_\C\\\@<!&trianglelefteq;_\&#x22b4;_geI
  sm_\C\\\@<!&triangleq;_\&#x225c;_geI
  sm_\C\\\@<!&triangleright;_\&#x25b9;_geI
  sm_\C\\\@<!&trianglerighteq;_\&#x22b5;_geI
  sm_\C\\\@<!&tridot;_\&#x25ec;_geI
  sm_\C\\\@<!&trie;_\&#x225c;_geI
  sm_\C\\\@<!&triminus;_\&#x2a3a;_geI
  sm_\C\\\@<!&TripleDot;_\&#x20db;_geI
  sm_\C\\\@<!&triplus;_\&#x2a39;_geI
  sm_\C\\\@<!&trisb;_\&#x29cd;_geI
  sm_\C\\\@<!&tritime;_\&#x2a3b;_geI
  sm_\C\\\@<!&trpezium;_\&#x2300;_geI
  sm_\C\\\@<!&Tscr;_\&#x1d4af;_geI
  sm_\C\\\@<!&tscr;_\&#x1d4c9;_geI
  sm_\C\\\@<!&TScy;_\&#x426;_geI
  sm_\C\\\@<!&tscy;_\&#x446;_geI
  sm_\C\\\@<!&TSHcy;_\&#x40b;_geI
  sm_\C\\\@<!&tshcy;_\&#x45b;_geI
  sm_\C\\\@<!&Tstrok;_\&#x166;_geI
  sm_\C\\\@<!&tstrok;_\&#x167;_geI
  sm_\C\\\@<!&twixt;_\&#x226c;_geI
  sm_\C\\\@<!&twoheadleftarrow;_\&#x219e;_geI
  sm_\C\\\@<!&twoheadrightarrow;_\&#x21a0;_geI
  sm_\C\\\@<!&Uarr;_\&#x219f;_geI
  sm_\C\\\@<!&Uarrocir;_\&#x2949;_geI
  sm_\C\\\@<!&Ubrcy;_\&#x40e;_geI
  sm_\C\\\@<!&ubrcy;_\&#x45e;_geI
  sm_\C\\\@<!&Ubreve;_\&#x16c;_geI
  sm_\C\\\@<!&ubreve;_\&#x16d;_geI
  sm_\C\\\@<!&Ucy;_\&#x423;_geI
  sm_\C\\\@<!&ucy;_\&#x443;_geI
  sm_\C\\\@<!&udarr;_\&#x21c5;_geI
  sm_\C\\\@<!&Udblac;_\&#x170;_geI
  sm_\C\\\@<!&udblac;_\&#x171;_geI
  sm_\C\\\@<!&udhar;_\&#x296e;_geI
  sm_\C\\\@<!&ufisht;_\&#x297e;_geI
  sm_\C\\\@<!&Ufr;_\&#x1d518;_geI
  sm_\C\\\@<!&ufr;_\&#x1d532;_geI
  sm_\C\\\@<!&uHar;_\&#x2963;_geI
  sm_\C\\\@<!&uharl;_\&#x21bf;_geI
  sm_\C\\\@<!&uharr;_\&#x21be;_geI
  sm_\C\\\@<!&uhblk;_\&#x2580;_geI
  sm_\C\\\@<!&ulcorn;_\&#x231c;_geI
  sm_\C\\\@<!&ulcorner;_\&#x231c;_geI
  sm_\C\\\@<!&ulcrop;_\&#x230f;_geI
  sm_\C\\\@<!&ultri;_\&#x25f8;_geI
  sm_\C\\\@<!&Umacr;_\&#x16a;_geI
  sm_\C\\\@<!&umacr;_\&#x16b;_geI
  if a:q=~'s'|sm_\C\\\@<!&UnderBar;_\&#x5f;_geI|endif
  sm_\C\\\@<!&UnderBrace;_\&#x23df;_geI
  sm_\C\\\@<!&UnderBracket;_\&#x23b5;_geI
  sm_\C\\\@<!&UnderParenthesis;_\&#x23dd;_geI
  sm_\C\\\@<!&Union;_\&#x22c3;_geI
  sm_\C\\\@<!&UnionPlus;_\&#x228e;_geI
  sm_\C\\\@<!&Uogon;_\&#x172;_geI
  sm_\C\\\@<!&uogon;_\&#x173;_geI
  sm_\C\\\@<!&Uopf;_\&#x1d54c;_geI
  sm_\C\\\@<!&uopf;_\&#x1d566;_geI
  sm_\C\\\@<!&UpArrow;_\&#x2191;_geI
  sm_\C\\\@<!&Uparrow;_\&#x21d1;_geI
  sm_\C\\\@<!&uparrow;_\&#x2191;_geI
  sm_\C\\\@<!&UpArrowBar;_\&#x2912;_geI
  sm_\C\\\@<!&UpArrowDownArrow;_\&#x21c5;_geI
  sm_\C\\\@<!&UpDownArrow;_\&#x2195;_geI
  sm_\C\\\@<!&Updownarrow;_\&#x21d5;_geI
  sm_\C\\\@<!&updownarrow;_\&#x2195;_geI
  sm_\C\\\@<!&UpEquilibrium;_\&#x296e;_geI
  sm_\C\\\@<!&upharpoonleft;_\&#x21bf;_geI
  sm_\C\\\@<!&upharpoonright;_\&#x21be;_geI
  sm_\C\\\@<!&uplus;_\&#x228e;_geI
  sm_\C\\\@<!&UpperLeftArrow;_\&#x2196;_geI
  sm_\C\\\@<!&UpperRightArrow;_\&#x2197;_geI
  sm_\C\\\@<!&Upsi;_\&#x3d2;_geI
  sm_\C\\\@<!&upsi;_\&#x3c5;_geI
  sm_\C\\\@<!&UpTee;_\&#x22a5;_geI
  sm_\C\\\@<!&UpTeeArrow;_\&#x21a5;_geI
  sm_\C\\\@<!&upuparrows;_\&#x21c8;_geI
  sm_\C\\\@<!&urcorn;_\&#x231d;_geI
  sm_\C\\\@<!&urcorner;_\&#x231d;_geI
  sm_\C\\\@<!&urcrop;_\&#x230e;_geI
  sm_\C\\\@<!&Uring;_\&#x16e;_geI
  sm_\C\\\@<!&uring;_\&#x16f;_geI
  sm_\C\\\@<!&urtri;_\&#x25f9;_geI
  sm_\C\\\@<!&Uscr;_\&#x1d4b0;_geI
  sm_\C\\\@<!&uscr;_\&#x1d4ca;_geI
  sm_\C\\\@<!&utdot;_\&#x22f0;_geI
  sm_\C\\\@<!&Utilde;_\&#x168;_geI
  sm_\C\\\@<!&utilde;_\&#x169;_geI
  sm_\C\\\@<!&utri;_\&#x25b5;_geI
  sm_\C\\\@<!&utrif;_\&#x25b4;_geI
  sm_\C\\\@<!&uuarr;_\&#x21c8;_geI
  sm_\C\\\@<!&uwangle;_\&#x29a7;_geI
  sm_\C\\\@<!&vangrt;_\&#x299c;_geI
  sm_\C\\\@<!&varepsilon;_\&#x3f5;_geI
  sm_\C\\\@<!&varkappa;_\&#x3f0;_geI
  sm_\C\\\@<!&varnothing;_\&#x2205;_geI
  sm_\C\\\@<!&varphi;_\&#x3d5;_geI
  sm_\C\\\@<!&varpi;_\&#x3d6;_geI
  sm_\C\\\@<!&varpropto;_\&#x221d;_geI
  sm_\C\\\@<!&vArr;_\&#x21d5;_geI
  sm_\C\\\@<!&varr;_\&#x2195;_geI
  sm_\C\\\@<!&varrho;_\&#x3f1;_geI
  sm_\C\\\@<!&varsigma;_\&#x3c2;_geI
  sm_\C\\\@<!&vartheta;_\&#x3d1;_geI
  sm_\C\\\@<!&vartriangleleft;_\&#x22b2;_geI
  sm_\C\\\@<!&vartriangleright;_\&#x22b3;_geI
  sm_\C\\\@<!&Vbar;_\&#x2aeb;_geI
  sm_\C\\\@<!&vBar;_\&#x2ae8;_geI
  sm_\C\\\@<!&vBarv;_\&#x2ae9;_geI
  sm_\C\\\@<!&Vcy;_\&#x412;_geI
  sm_\C\\\@<!&vcy;_\&#x432;_geI
  sm_\C\\\@<!&VDash;_\&#x22ab;_geI
  sm_\C\\\@<!&Vdash;_\&#x22a9;_geI
  sm_\C\\\@<!&vDash;_\&#x22a8;_geI
  sm_\C\\\@<!&vdash;_\&#x22a2;_geI
  sm_\C\\\@<!&Vdashl;_\&#x2ae6;_geI
  sm_\C\\\@<!&Vee;_\&#x22c1;_geI
  sm_\C\\\@<!&vee;_\&#x2228;_geI
  sm_\C\\\@<!&veebar;_\&#x22bb;_geI
  sm_\C\\\@<!&veeeq;_\&#x225a;_geI
  sm_\C\\\@<!&vellip;_\&#x22ee;_geI
  sm_\C\\\@<!&Verbar;_\&#x2016;_geI
  if a:q=~'s'|sm_\C\\\@<!&verbar;_\&#x7c;_geI|endif
  sm_\C\\\@<!&Vert;_\&#x2016;_geI
  if a:q=~'s'|sm_\C\\\@<!&vert;_\&#x7c;_geI|endif
  sm_\C\\\@<!&VerticalBar;_\&#x2223;_geI
  if a:q=~'s'|sm_\C\\\@<!&VerticalLine;_\&#x7c;_geI|endif
  sm_\C\\\@<!&VerticalSeparator;_\&#x2758;_geI
  sm_\C\\\@<!&VerticalTilde;_\&#x2240;_geI
  sm_\C\\\@<!&VeryThinSpace;_\&#x200a;_geI
  sm_\C\\\@<!&Vfr;_\&#x1d519;_geI
  sm_\C\\\@<!&vfr;_\&#x1d533;_geI
  sm_\C\\\@<!&vltri;_\&#x22b2;_geI
  sm_\C\\\@<!&Vopf;_\&#x1d54d;_geI
  sm_\C\\\@<!&vopf;_\&#x1d567;_geI
  sm_\C\\\@<!&vprop;_\&#x221d;_geI
  sm_\C\\\@<!&vrtri;_\&#x22b3;_geI
  sm_\C\\\@<!&Vscr;_\&#x1d4b1;_geI
  sm_\C\\\@<!&vscr;_\&#x1d4cb;_geI
  sm_\C\\\@<!&Vvdash;_\&#x22aa;_geI
  sm_\C\\\@<!&vzigzag;_\&#x299a;_geI
  sm_\C\\\@<!&Wcirc;_\&#x174;_geI
  sm_\C\\\@<!&wcirc;_\&#x175;_geI
  sm_\C\\\@<!&wedbar;_\&#x2a5f;_geI
  sm_\C\\\@<!&Wedge;_\&#x22c0;_geI
  sm_\C\\\@<!&wedge;_\&#x2227;_geI
  sm_\C\\\@<!&wedgeq;_\&#x2259;_geI
  sm_\C\\\@<!&Wfr;_\&#x1d51a;_geI
  sm_\C\\\@<!&wfr;_\&#x1d534;_geI
  sm_\C\\\@<!&Wopf;_\&#x1d54e;_geI
  sm_\C\\\@<!&wopf;_\&#x1d568;_geI
  sm_\C\\\@<!&wp;_\&#x2118;_geI
  sm_\C\\\@<!&wr;_\&#x2240;_geI
  sm_\C\\\@<!&wreath;_\&#x2240;_geI
  sm_\C\\\@<!&Wscr;_\&#x1d4b2;_geI
  sm_\C\\\@<!&wscr;_\&#x1d4cc;_geI
  sm_\C\\\@<!&xcap;_\&#x22c2;_geI
  sm_\C\\\@<!&xcirc;_\&#x25ef;_geI
  sm_\C\\\@<!&xcup;_\&#x22c3;_geI
  sm_\C\\\@<!&xdtri;_\&#x25bd;_geI
  sm_\C\\\@<!&Xfr;_\&#x1d51b;_geI
  sm_\C\\\@<!&xfr;_\&#x1d535;_geI
  sm_\C\\\@<!&xhArr;_\&#x27fa;_geI
  sm_\C\\\@<!&xharr;_\&#x27f7;_geI
  sm_\C\\\@<!&xlArr;_\&#x27f8;_geI
  sm_\C\\\@<!&xlarr;_\&#x27f5;_geI
  sm_\C\\\@<!&xmap;_\&#x27fc;_geI
  sm_\C\\\@<!&xnis;_\&#x22fb;_geI
  sm_\C\\\@<!&xodot;_\&#x2a00;_geI
  sm_\C\\\@<!&Xopf;_\&#x1d54f;_geI
  sm_\C\\\@<!&xopf;_\&#x1d569;_geI
  sm_\C\\\@<!&xoplus;_\&#x2a01;_geI
  sm_\C\\\@<!&xotime;_\&#x2a02;_geI
  sm_\C\\\@<!&xrArr;_\&#x27f9;_geI
  sm_\C\\\@<!&xrarr;_\&#x27f6;_geI
  sm_\C\\\@<!&Xscr;_\&#x1d4b3;_geI
  sm_\C\\\@<!&xscr;_\&#x1d4cd;_geI
  sm_\C\\\@<!&xsqcup;_\&#x2a06;_geI
  sm_\C\\\@<!&xuplus;_\&#x2a04;_geI
  sm_\C\\\@<!&xutri;_\&#x25b3;_geI
  sm_\C\\\@<!&xvee;_\&#x22c1;_geI
  sm_\C\\\@<!&xwedge;_\&#x22c0;_geI
  sm_\C\\\@<!&YAcy;_\&#x42f;_geI
  sm_\C\\\@<!&yacy;_\&#x44f;_geI
  sm_\C\\\@<!&Ycirc;_\&#x176;_geI
  sm_\C\\\@<!&ycirc;_\&#x177;_geI
  sm_\C\\\@<!&Ycy;_\&#x42b;_geI
  sm_\C\\\@<!&ycy;_\&#x44b;_geI
  sm_\C\\\@<!&Yfr;_\&#x1d51c;_geI
  sm_\C\\\@<!&yfr;_\&#x1d536;_geI
  sm_\C\\\@<!&YIcy;_\&#x407;_geI
  sm_\C\\\@<!&yicy;_\&#x457;_geI
  sm_\C\\\@<!&Yopf;_\&#x1d550;_geI
  sm_\C\\\@<!&yopf;_\&#x1d56a;_geI
  sm_\C\\\@<!&Yscr;_\&#x1d4b4;_geI
  sm_\C\\\@<!&yscr;_\&#x1d4ce;_geI
  sm_\C\\\@<!&YUcy;_\&#x42e;_geI
  sm_\C\\\@<!&yucy;_\&#x44e;_geI
  sm_\C\\\@<!&Zacute;_\&#x179;_geI
  sm_\C\\\@<!&zacute;_\&#x17a;_geI
  sm_\C\\\@<!&Zcaron;_\&#x17d;_geI
  sm_\C\\\@<!&zcaron;_\&#x17e;_geI
  sm_\C\\\@<!&Zcy;_\&#x417;_geI
  sm_\C\\\@<!&zcy;_\&#x437;_geI
  sm_\C\\\@<!&Zdot;_\&#x17b;_geI
  sm_\C\\\@<!&zdot;_\&#x17c;_geI
  sm_\C\\\@<!&zeetrf;_\&#x2128;_geI
  sm_\C\\\@<!&ZeroWidthSpace;_\&#x200b;_geI
  sm_\C\\\@<!&Zfr;_\&#x2128;_geI
  sm_\C\\\@<!&zfr;_\&#x1d537;_geI
  sm_\C\\\@<!&ZHcy;_\&#x416;_geI
  sm_\C\\\@<!&zhcy;_\&#x436;_geI
  sm_\C\\\@<!&zigrarr;_\&#x21dd;_geI
  sm_\C\\\@<!&Zopf;_\&#x2124;_geI
  sm_\C\\\@<!&zopf;_\&#x1d56b;_geI
  sm_\C\\\@<!&Zscr;_\&#x1d4b5;_geI
  sm_\C\\\@<!&zscr;_\&#x1d4cf;_geI
endfunction